In [31]:
import pandas as pd

# Read the RTI-final.csv file
rti_final_df = pd.read_csv('RTI-final.csv')

# Read the SA-zones.csv file
sa_zones_df = pd.read_csv('SA-zones.csv')

# Merge zone attributes to RTi-final based on SA2_CODE21 variable (0_ZID in SA-zones file)
df = pd.merge(rti_final_df, sa_zones_df, how='left', left_on='SA2_CODE21', right_on='0_ZID')

# Display the merged dataframe
print(df)

       Incident ID Main_Category  Longitude  Latitude        Start_Time
0                1         Crash    151.058  -33.9431  14-08-2018 19:21  \
1                2     Breakdown    151.159  -33.8096  15-08-2018 00:47
2                3         Crash    150.875  -33.7344  15-08-2018 01:12
3                4         Crash    150.973  -33.8172  15-08-2018 01:27
4                5         Crash    150.981  -33.7919  15-08-2018 01:37
...            ...           ...        ...       ...               ...
85606        85607     Breakdown    151.193  -33.8877  14-08-2018 08:09
85607        85608         Crash    151.054  -33.7991  15-08-2018 04:44
85608        85609         Crash    151.066  -33.7527  15-08-2018 04:45
85609        85610     Breakdown    151.154  -33.7587  15-08-2018 04:47
85610        85611     Breakdown    151.196  -33.9220  15-08-2018 04:50

           Last_Updated        Day          End_Time  Duration_in_Minutes
0      14-08-2018 20:00    Tuesday  14-08-2018 20:00            39.319950  \
1      15-08-2018 00:59  Wednesday  15-08-2018 00:59            12.029000
2      15-08-2018 01:29  Wednesday  15-08-2018 01:29            16.956667
3      15-08-2018 02:09  Wednesday  15-08-2018 02:09            42.804117
4      15-08-2018 02:18  Wednesday  15-08-2018 02:18            40.840000
...                 ...        ...               ...                  ...
85606  14-08-2018 08:09    Tuesday           UNKNOWN             0.073550
85607  15-08-2018 04:44  Wednesday           UNKNOWN             0.000000
85608  15-08-2018 04:45  Wednesday           UNKNOWN             0.000000
85609  15-08-2018 04:47  Wednesday           UNKNOWN             0.000000
85610  15-08-2018 04:50  Wednesday           UNKNOWN             0.000000

         Primary_Vehicle  Secondary_Vehicle
0                    Car                Car  \
1                    Car                NaN
2                    Car                NaN
3                  Truck                Car
4      Multiple vehicles  Multiple vehicles
...                  ...                ...
85606                Car            Unknown
85607            Unknown            Unknown
85608  Multiple vehicles            Unknown
85609              Truck            Unknown
85610                Bus            Unknown

                                  Attending_Groups         Display_Name
0                           ['Emergency services']      accident 2 cars  \
1                                ['Motorway Crew']        breakdown car
2          ['Emergency services', 'Motorway Crew']         accident car
3      ['Emergency services', 'Transport for NSW']         accident car
4                                    ['Tow Truck']  accident 3 vehicles
...                                            ...                  ...
85606                         ['RMS', 'Tow truck']        BREAKDOWN Car
85607                         ['RMS', 'Tow truck']      ACCIDENT 2 cars
85608                                           []  ACCIDENT 3 vehicles
85609                                      ['RMS']      BREAKDOWN Truck
85610                                      ['RMS']        BREAKDOWN Bus

       Is_Major_Incident Diversions                 Advice_A
0                  False    unknown         Exercise caution  \
1                  False    unknown         Exercise caution
2                  False    unknown                      NaN
3                  False    unknown         Exercise caution
4                  False    unknown         Exercise caution
...                  ...        ...                      ...
85606              False        NaN                      NaN
85607              False        NaN                      NaN
85608              False        NaN  Allow extra travel time
85609              False        NaN  Allow extra travel time
85610              False        NaN         Exercise caution

                      Advice_B Other_Advice  Closure_Type   Direction
0      Allow extra travel time      unknown      Affected   Eastbound  \
1                          NaN      unknown  Lanes closed   Westbound
2                          NaN      unknown  Lanes closed   Westbound
3      Allow extra travel time      unknown      Affected   Westbound
4                          NaN      unknown      Affected  Southbound
...                        ...          ...           ...         ...
85606                      NaN          NaN  Lanes closed   Westbound
85607                      NaN          NaN  Lanes closed   Eastbound
85608                      NaN          NaN      Affected  Southbound
85609                      NaN          NaN  Lanes closed  Southbound
85610           Avoid the area          NaN  Lanes closed  Northbound

                Main_Street  Affected_Lanes  Actual_Number_of_Lanes
0               M5 Motorway              99                       99  \
1          Lane Cove Tunnel               1                        2
2      Westlink M7 off-ramp               1                        1
3               M4 Motorway               1                        1
4          Old Windsor Road              99                       99
...                     ...             ...                      ...
85606      Cleveland Street              99                       99
85607    Kissing Point Road               1                        2
85608         Beecroft Road              99                       99
85609       Pacific Highway               1                        2
85610           Botany Road               1                        1

                     Suburb Traffic_Volume  SA2_CODE21
0                 Riverwood        Unknown   119021366  \
1           Lane Cove North        Unknown   121011399
2              Quakers Hill        Unknown   116011304
3      South Wentworthville       Moderate   125041589
4                 Northmead        Unknown   125041493
...                     ...            ...         ...
85606            Camperdown        Unknown   117031638
85607                Dundas        Unknown   125021477
85608              Beecroft          Heavy   126011496
85609                Gordon       Moderate   121031407
85610            Alexandria        Unknown   117011635

                               SA2_NAME21  SA3_CODE21              SA3_NAME21
0                               Punchbowl       11902              Canterbury  \
1      Chatswood (West) - Lane Cove North       12101   Chatswood - Lane Cove
2            Blacktown (North) - Marayong       11601               Blacktown
3               Wentworthville - Westmead       12504              Parramatta
4          Toongabbie - Constitution Hill       12504              Parramatta
...                                   ...         ...                     ...
85606             Camperdown - Darlington       11703       Sydney Inner City
85607               Ermington - Rydalmere       12502             Carlingford
85608          Pennant Hills - Cheltenham       12601  Pennant Hills - Epping
85609                    Gordon - Killara       12103             Ku-ring-gai
85610                              Mascot       11701                  Botany

       SA4_CODE21                         SA4_NAME21  AREASQKM21
0             119          Sydney - Inner South West      5.2458  \
1             121  Sydney - North Sydney and Hornsby      5.5372
2             116                 Sydney - Blacktown      7.3828
3             125                Sydney - Parramatta      3.9355
4             125                Sydney - Parramatta      7.4795
...           ...                                ...         ...
85606         117      Sydney - City and Inner South      1.7106
85607         125                Sydney - Parramatta      9.8655
85608         126                      Sydney - Ryde     13.2936
85609         121  Sydney - North Sydney and Hornsby     11.6713
85610         117      Sydney - City and Inner South      3.0501

                                              LOCI_URI21      0_ZID   1_Area
0      http://linked.data.gov.au/dataset/asgsed3/SA2/...  119021366   5.2458  \
1      http://linked.data.gov.au/dataset/asgsed3/SA2/...  121011399   5.5372
2      http://linked.data.gov.au/dataset/asgsed3/SA2/...  116011304   7.3828
3      http://linked.data.gov.au/dataset/asgsed3/SA2/...  125041589   3.9355
4      http://linked.data.gov.au/dataset/asgsed3/SA2/...  125041493   7.4795
...                                                  ...        ...      ...
85606  http://linked.data.gov.au/dataset/asgsed3/SA2/...  117031638   1.7106
85607  http://linked.data.gov.au/dataset/asgsed3/SA2/...  125021477   9.8655
85608  http://linked.data.gov.au/dataset/asgsed3/SA2/...  126011496  13.2936
85609  http://linked.data.gov.au/dataset/asgsed3/SA2/...  121031407  11.6713
85610  http://linked.data.gov.au/dataset/asgsed3/SA2/...  117011635   3.0501

            2_ML      3_TRL      4_PRL     5_SRL     6_TrRL      7_RRL
0       7.488104   3.038780   2.236683  6.602571   2.551265  42.103090  \
1       8.365015   2.097842   7.903368  4.617769   0.232704  40.351141
2       9.051683   0.000000  12.307502  5.297219   9.525819  56.104489
3       9.698544   8.941532   0.016410  1.416884   5.140331  32.486126
4       0.000000   9.092391   0.000000  7.092430  13.338771  51.982067
...          ...        ...        ...       ...        ...        ...
85606   0.000000   6.229383   0.770780  1.555551   2.349888  12.909696
85607   0.000000  21.451793   9.077881  1.305794  13.243906  62.631529
85608  32.246711   8.952339   7.362372  2.310562   5.986376  67.291924
85609   0.000000   8.402822   0.000000  3.362577   9.581556  72.142489
85610   7.158851   0.000000  15.885392  3.114614   3.556988  19.325149

         8_LsRL     9_URL     10_ToRL    11_EoR  12_NoN  13_NDEs  14_NNC2L
0      0.000000  0.115587   64.136080  0.504771     325       40         7  \
1      0.000000  0.739679   64.307518  0.515889     269       59         6
2      0.000000  0.128916   92.415628  0.523895     468      112         2
3      0.000000  0.512046   58.211873  0.547443     266       39         7
4      0.000000  4.266734   85.772393  0.515169     454      105         3
...         ...       ...         ...       ...     ...      ...       ...
85606  0.974891  0.628599   25.418788  0.609042     156       17         5
85607  0.000000  5.247824  112.958727  0.560480     607      100         5
85608  0.000000  1.074018  125.224302  0.563783     460      115         5
85609  0.000000  0.000000   93.489444  0.334247     412       81         0
85610  0.000000  3.525824   52.566818  0.665311     274       25         1

       15_NNC3L  16_NNC4L    17_AND  18_NE    19_MCI    20_CoI  21 NBS
0           260        17  2.790769    491  0.258915  0.001351     210  \
1           176        28  2.643123    383  0.215760  0.001839     210
2           307        47  2.617521    631  0.176155  0.001177     234
3           188        31  2.804511    402  0.259962  0.001650     174
4           322        23  2.585903    598  0.160576  0.001272     194
...         ...       ...       ...    ...       ...       ...     ...
85606       105        29  2.935897    275  0.390879  0.002070      44
85607       408        92  2.823723    881  0.227461  0.000783     293
85608       296        41  2.597826    627  0.183607  0.001172     216
85609       289        41  2.711165    577  0.202686  0.001240     220
85610       188        58  3.043796    448  0.322284  0.001368      90

        22_CA   23_EA   24_HA   25_IA  26_OA   27_PA  28_PrA   29_RA   30_TA
0      0.0938  0.1211  0.0000  0.7056    0.0  0.5171     0.0  3.8082  0.0000  \
1      0.0080  0.1223  0.0238  0.0000    0.0  1.3725     0.0  4.0106  0.0000
2      0.0000  0.2768  0.0000  0.3180    0.0  0.9027     0.0  5.6929  0.1924
3      0.1010  0.1006  0.0236  0.0000    0.0  0.2426     0.0  3.1727  0.2950
4      0.4036  0.1788  0.0000  0.0000    0.0  0.8217     0.0  6.0754  0.0000
...       ...     ...     ...     ...    ...     ...     ...     ...     ...
85606  0.1061  0.7496  0.0680  0.0285    0.0  0.1834     0.0  0.5750  0.0000
85607  1.8816  0.5680  0.0609  0.1085    0.0  1.3128     0.0  5.6133  0.0000
85608  0.2145  0.3761  0.0000  0.0000    0.0  4.6254     0.0  8.0776  0.0000
85609  0.1110  0.1334  0.0000  0.0000    0.0  3.6925     0.0  7.7344  0.0000
85610  0.1779  0.0834  0.0000  0.7949    0.0  0.1966     0.0  1.6856  0.1117

       31_WbA   32_EoLU  33_TP   34_PD0MV   35_PD1MV   36_PD2MV   37_PD3MV
0      0.0000  0.386385  21537  11.297837  37.886855  30.565724  12.296173  \
1      0.0000  0.302463  21270  10.253288  52.715538  29.067219   5.723332
2      0.0000  0.352217  20570   8.724832  41.000610  34.716290  10.600976
3      0.0000  0.329226  21564  13.219616  56.830135  22.857143   4.804549
4      0.0000  0.285901  22840   8.134605  39.745628  35.466349  10.996290
...       ...       ...    ...        ...        ...        ...        ...
85606  0.0000  0.580342   8323  25.450139  53.116343  17.659280   2.770083
85607  0.3204  0.548046  24612   8.555502  37.190984  37.869607  10.954920
85608  0.0000  0.363720  21731   4.697707  35.830438  41.987491  11.994441
85609  0.0000  0.317965  22430   5.592784  41.778351  38.298969   9.716495
85610  0.0000  0.538610  21581  20.092988  50.389545  22.970596   4.687107

       38_PD≥4MV     39_PUE  40_AMI  41_NPTtWbyPT  42_NPTtWbyTx  43_NPTtWbyCD
0       7.953411  12.109393     831           342            16          2806  \
1       2.240623   7.776211    1643           651             6          2652
2       4.957291   9.688867    1030           532            18          3686
3       2.288557   9.956409    1302           902            11          2707
4       5.657128   9.071804    1170           589            18          3487
...          ...        ...     ...           ...           ...           ...
85606   1.004155   8.626697    1457           347            10           726
85607   5.428987   9.198765    1177           347            12          4061
85608   5.489924   8.872118    1557           422             0          2902
85609   4.613402  11.310745    1666           543             6          2627
85610   1.859764   9.123766    1314          1639            37          3013

       44_NPTtWbyCP  45_NPTtWbyO  46_NPWfH   47_PWCJH   48_PBCJH  49_ANP_FH
0               276          260      1520  67.634460  32.365540   3.713468
1               227          514      6070  88.007396  11.992604   3.023239
2               323          256      2398  67.554766  32.445234   3.341706
3               291          311      4379  78.956666  21.043334   3.248887
4               314          261      3798  77.384802  22.615198   3.295874
...             ...          ...       ...        ...        ...        ...
85606            68          587      2683  89.198132  10.801868   2.643437
85607           298          276      4287  80.158441  19.841559   3.276092
85608           224          282      5386  88.021691  11.978309   3.281978
85609           197          228      5729  88.403846  11.596154   3.189215
85610           309          903      4585  78.280807  21.719193   2.976042

[85611 rows x 83 columns]

In [32]:
def analyze_data(df):
    """
    Print column names, top 2 most frequent values from each column, and type of each column.

    Parameters:
    df (pandas.DataFrame): The data frame to analyze.
    """
    for column in df.columns:
        print(f"Column: {column}")
        print(f"Type: {df[column].dtype}")
        print("Top 20 most frequent values:")
        print(df[column].value_counts().head(20))
        print("\n")

analyze_data(df)

Column: Incident ID
Type: int64
Top 20 most frequent values:
Incident ID
1        1
57081    1
57079    1
57078    1
57077    1
57076    1
57075    1
57074    1
57073    1
57072    1
57071    1
57070    1
57069    1
57068    1
57067    1
57066    1
57065    1
57064    1
57063    1
57080    1
Name: count, dtype: int64


Column: Main_Category
Type: object
Top 20 most frequent values:
Main_Category
Breakdown    46085
Crash        39165
Other          361
Name: count, dtype: int64


Column: Longitude
Type: float64
Top 20 most frequent values:
Longitude
151.211    1000
151.213     977
151.214     912
151.218     782
151.212     731
151.193     710
151.217     690
151.210     598
151.215     536
151.064     506
151.065     441
151.192     431
151.067     427
151.209     416
151.205     394
151.084     393
151.048     389
151.153     386
151.206     385
151.020     384
Name: count, dtype: int64


Column: Latitude
Type: float64
Top 20 most frequent values:
Latitude
-33.9362    316
-33.8435    212
-33.8310    211
-33.8679    208
-33.8270    197
-33.9361    187
-33.9295    185
-33.9459    166
-33.8749    161
-33.9363    156
-33.8569    147
-33.8276    143
-33.8753    142
-33.7586    142
-33.8268    134
-33.9446    126
-33.9461    122
-33.8747    121
-33.7395    120
-33.9009    117
Name: count, dtype: int64


Column: Start_Time
Type: object
Top 20 most frequent values:
Start_Time
21-06-2019 07:51    3
29-03-2018 12:41    3
09-11-2019 07:52    3
12-02-2019 04:38    3
28-09-2018 06:15    3
08-03-2018 03:07    3
05-04-2017 07:08    2
03-06-2019 10:27    2
25-03-2019 10:11    2
08-05-2019 10:08    2
11-03-2020 02:37    2
06-10-2018 14:33    2
16-03-2017 04:31    2
07-09-2018 03:53    2
16-03-2017 04:19    2
17-07-2018 09:17    2
14-02-2018 12:24    2
27-04-2018 08:40    2
04-12-2017 11:21    2
19-09-2019 06:10    2
Name: count, dtype: int64


Column: Last_Updated
Type: object
Top 20 most frequent values:
Last_Updated
13-02-2021 11:10    4
03-05-2017 06:25    4
05-07-2017 06:54    4
08-02-2019 11:56    3
04-10-2018 14:50    3
22-07-2019 04:26    3
14-03-2018 14:17    3
17-07-2020 13:35    3
11-07-2018 08:18    3
25-05-2019 15:39    3
07-08-2017 12:14    3
17-02-2022 02:55    3
17-09-2020 09:00    3
20-06-2022 07:57    3
03-06-2017 09:40    3
10-02-2017 10:27    3
08-06-2018 13:20    3
12-04-2018 13:21    3
24-02-2021 13:12    3
29-03-2018 13:32    3
Name: count, dtype: int64


Column: Day
Type: object
Top 20 most frequent values:
Day
Friday       14482
Thursday     14395
Wednesday    14051
Tuesday      13573
Monday       12771
Saturday      9401
Sunday        6938
Name: count, dtype: int64


Column: End_Time
Type: object
Top 20 most frequent values:
End_Time
UNKNOWN             1213
05-07-2017 06:54       4
13-02-2021 11:10       4
03-05-2017 06:25       4
12-04-2017 14:54       3
01-02-2017 01:46       3
06-02-2017 05:00       3
09-02-2017 11:19       3
10-02-2017 10:27       3
05-09-2018 02:06       3
01-04-2020 02:31       3
21-03-2017 11:30       3
07-04-2017 02:50       3
29-04-2017 14:32       3
03-02-2020 13:22       3
17-06-2020 05:23       3
08-05-2017 04:42       3
11-09-2018 12:55       3
17-07-2018 10:39       3
27-05-2017 12:24       3
Name: count, dtype: int64


Column: Duration_in_Minutes
Type: float64
Top 20 most frequent values:
Duration_in_Minutes
0.000000     92
0.000500     68
0.000783     50
0.000550     32
0.000767     31
0.000833     12
0.000567     11
23.364333     4
21.822833     3
25.677783     3
3.564000      3
17.709167     3
4.985667      3
11.188050     3
54.947667     3
22.683717     3
29.195400     3
33.112950     3
45.652667     3
4.779333      3
Name: count, dtype: int64


Column: Primary_Vehicle
Type: object
Top 20 most frequent values:
Primary_Vehicle
Car                  49806
Truck                14914
Unknown               9682
Multiple vehicles     6537
Bus                   3479
Motorcycle            1051
Others                 142
Name: count, dtype: int64


Column: Secondary_Vehicle
Type: object
Top 20 most frequent values:
Secondary_Vehicle
Car                  18858
Unknown              10457
Multiple vehicles     6500
Motorcycle            1629
Pedestrian             962
Bicycle                380
Truck                  255
Bus                     63
Others                   6
Name: count, dtype: int64


Column: Attending_Groups
Type: object
Top 20 most frequent values:
Attending_Groups
['Transport for NSW']                                       13101
['Emergency services', 'Transport for NSW']                 11347
unknown                                                     10927
['Emergency services']                                       8988
['RMS']                                                      7236
['Emergency service(s)', 'RMS']                              6252
['Emergency service(s)']                                     5257
['Motorway Crew']                                            4034
['Motorway crew']                                            1997
['Emergency services', 'Tow Truck']                          1332
['Tow Truck', 'Transport for NSW']                           1171
['Emergency services', 'Tow Truck', 'Transport for NSW']     1008
['Transport for NSW', 'Emergency services']                   963
['Mechanic']                                                  842
['Heavy vehicle tow truck', 'Transport for NSW']              744
['Emergency services', 'Motorway Crew']                       704
['Tow Truck']                                                 670
['Tow truck']                                                 632
['Mechanic', 'Transport for NSW']                             556
['Emergency service(s)', 'Tow truck']                         503
Name: count, dtype: int64


Column: Display_Name
Type: object
Top 20 most frequent values:
Display_Name
breakdown car                 28374
breakdown truck               10985
crash 2 cars                   9178
accident 2 cars                5943
accident car                   3453
crash car                      2704
breakdown bus                  2647
crash 3 vehicles               1724
accident 3 vehicles            1527
crash multiple vehicles        1351
crash truck, car               1308
accident truck, car            1138
breakdown van                   969
crash car, motorcycle           817
accident multiple vehicles      774
accident car, motorcycle        620
crash 3 cars                    507
crash car, pedestrian           463
BREAKDOWN Car                   447
breakdown semi trailer          416
Name: count, dtype: int64


Column: Is_Major_Incident
Type: bool
Top 20 most frequent values:
Is_Major_Incident
False    84140
True      1471
Name: count, dtype: int64


Column: Diversions
Type: object
Top 20 most frequent values:
Diversions
unknown                                                                                                    83591
Local diversions in place.&nbsp;                                                                              24
Local diversions in place.                                                                                    14
Local diversions are in place.                                                                                 9
<p><strong>&nbsp;</strong></p>                                                                                 9
Local diversions are in place.&nbsp;                                                                           7
Local diversions available.&nbsp;                                                                              5
Local diversions are available.&nbsp;                                                                          4
Local diversions.                                                                                              4
local diversions in place.&nbsp;                                                                               4
<strong></strong>                                                                                              3
<p>&nbsp;</p><p>&nbsp;</p>                                                                                     3
<p><strong></strong></p>                                                                                       3
Southbound traffic is diverted into Smithfield Rd, then local roads to return to Elizabeth Drive.&nbsp;        2
Local diversions are in place                                                                                  2
Local diversions for southbound traffic.&nbsp;                                                                 2
Eastbound motorists will detour via King Georges Rd, Stoney Creek Rd, Forest Rd and Marsh St.                  2
Local diversions for eastbound traffic.&nbsp;                                                                  2
Local diversons in place.                                                                                      2
Sussex St.                                                                                                     2
Name: count, dtype: int64


Column: Advice_A
Type: object
Top 20 most frequent values:
Advice_A
Exercise caution                  41382
Reduce your speed                 15254
Allow extra travel time            9939
Reduce speed                       6992
Expect delays                      6703
Reduced speed limit                 873
Use an alternative route            354
Use diversions                      288
Avoid the area                      281
Use alternative route                75
Police are directing traffic         73
Check signage                        56
Police directing traffic             27
Plan your journey                     8
Keep right                            6
Delay journey                         4
Keep left                             3
Delay your journey                    3
Merge left                            2
Don't drive through floodwater        2
Name: count, dtype: int64


Column: Advice_B
Type: object
Top 20 most frequent values:
Advice_B
Exercise caution                              31429
Allow extra travel time                       12141
Reduce your speed                              6323
Expect delays                                  4759
Reduce speed                                   1192
Use an alternative route                        159
Use alternative route                           147
Exercise caution, Allow extra travel time       137
Allow extra travel time, Exercise caution       115
Reduced speed limit                              94
Exercise caution; Allow extra travel time        81
Exercise caution, Expect delays                  80
Use diversions                                   75
Exercise caution, Reduce your speed              71
Reduce your speed, Exercise caution              54
Reduce your speed, Expect delays                 41
Check signage, Exercise caution                  41
Avoid the area                                   38
Expect delays, Exercise caution                  34
Reduce your speed, Allow extra travel time       33
Name: count, dtype: int64


Column: Other_Advice
Type: object
Top 20 most frequent values:
Other_Advice
unknown                                                                                                           83561
Alternating (stop/slow) traffic conditions are in place.                                                             14
Contra flow traffic conditions are in place to allow motorists to pass in both directions.                           13
Contraflow traffic conditions are in place.                                                                          12
Alternating (stop/slow) traffic conditions are in place to allow motorists to pass in one direction at a time.        9
The vehicle is in the centre median.                                                                                  7
<strong></strong>                                                                                                     4
There are no significant delays.                                                                                      3
Motorists are advised to expect intermittent stoppages for vehicle recovery.                                          3
A Stop/Slow is in operation.                                                                                          3
The vehicle is on the painted chevron.                                                                                3
A car has hit a pole.&nbsp;                                                                                           3
NOTE: Road closure lines provided by Google Maps may not be up to date.                                               2
All lanes are now open but there is heavy traffic.                                                                    2
All lanes are now open but traffic is heavy.                                                                          2
The truck is in the breakdown lane.&nbsp;                                                                             2
Contraflow traffic conditions will be in place.                                                                       2
All vehicles are in the parking lane.                                                                                 2
Traffic is heavy in both directions.&nbsp;                                                                            2
The accident is at the intersection.&nbsp;                                                                            2
Name: count, dtype: int64


Column: Closure_Type
Type: object
Top 20 most frequent values:
Closure_Type
Lanes closed    52691
Affected        30979
Closed           1630
unknown           306
Name: count, dtype: int64


Column: Direction
Type: object
Top 20 most frequent values:
Direction
Southbound         21744
Northbound         21374
Westbound          17683
Eastbound          16290
Both directions     4957
All directions      1708
City bound          1648
Outbound             177
Inbound               12
Name: count, dtype: int64


Column: Main_Street
Type: object
Top 20 most frequent values:
Main_Street
M4 Motorway              4740
Pennant Hills Road       2510
Parramatta Road          2191
Great Western Highway    2051
Hume Highway             1881
Princes Highway          1868
M5 East Motorway         1805
Victoria Road            1745
Pacific Highway          1700
Warringah Freeway        1687
M5 Motorway              1663
Eastern Distributor      1463
M1 Pacific Motorway      1356
King Georges Road        1241
Southern Cross Drive     1215
General Holmes Drive     1155
Cumberland Highway       1111
Western Distributor      1087
Centenary Drive           944
M7 Motorway               904
Name: count, dtype: int64


Column: Affected_Lanes
Type: int64
Top 20 most frequent values:
Affected_Lanes
1     50077
99    32414
2      3120
Name: count, dtype: int64


Column: Actual_Number_of_Lanes
Type: int64
Top 20 most frequent values:
Actual_Number_of_Lanes
99    36348
2     25274
1     13918
3      7362
4      2709
Name: count, dtype: int64


Column: Suburb
Type: object
Top 20 most frequent values:
Suburb
Sydney           2292
Mascot           2069
North Sydney     1861
Arncliffe        1318
Eastern Creek    1299
Cowan            1270
Moore Park       1007
Granville         995
Strathfield       957
Rozelle           937
Lidcombe          884
Beverly Hills     866
Ryde              831
Wahroonga         811
Greenacre         793
Greystanes        771
Liverpool         763
Pennant Hills     738
Holroyd           703
Casula            700
Name: count, dtype: int64


Column: Traffic_Volume
Type: object
Top 20 most frequent values:
Traffic_Volume
Unknown     65260
Heavy       15760
Moderate     4241
Light         350
Name: count, dtype: int64


Column: SA2_CODE21
Type: int64
Top 20 most frequent values:
SA2_CODE21
117031644    2518
121041417    2127
121021404    1821
125031481    1550
126011496    1542
117011325    1402
119041668    1289
116031318    1270
120021389    1179
125041718    1076
118011345    1041
120031396    1035
125041589     998
121021406     924
127031523     911
120031681     833
127031522     799
125011586     777
119031370     774
121031409     760
Name: count, dtype: int64


Column: SA2_NAME21
Type: object
Top 20 most frequent values:
SA2_NAME21
Sydney (North) - Millers Point          2518
North Sydney - Lavender Bay             2127
Berowra - Brooklyn - Cowan              1821
Granville - Clyde                       1550
Pennant Hills - Cheltenham              1542
Sydney Airport                          1402
Arncliffe - Bardwell Valley             1289
Prospect Reservoir                      1270
Lilyfield - Rozelle                     1179
Parramatta - South                      1076
Paddington - Moore Park                 1041
Homebush                                1035
Wentworthville - Westmead                998
Normanhurst - Thornleigh - Westleigh     924
Chipping Norton - Moorebank              911
Strathfield - West                       833
Casula                                   799
Lidcombe                                 777
Narwee - Beverly Hills                   774
Pymble                                   760
Name: count, dtype: int64


Column: SA3_CODE21
Type: int64
Top 20 most frequent values:
SA3_CODE21
11703    7729
12504    4965
12003    4002
11901    3912
12102    3749
12104    3712
11904    3367
11701    3292
12703    3231
12503    3052
12602    2886
11902    2673
11603    2460
12103    2290
12101    2241
12501    2166
12601    1888
11801    1870
12702    1863
12203    1815
Name: count, dtype: int64


Column: SA3_NAME21
Type: object
Top 20 most frequent values:
SA3_NAME21
Sydney Inner City                   7729
Parramatta                          4965
Strathfield - Burwood - Ashfield    4002
Bankstown                           3912
Hornsby                             3749
North Sydney - Mosman               3712
Kogarah - Rockdale                  3367
Botany                              3292
Liverpool                           3231
Merrylands - Guildford              3052
Ryde - Hunters Hill                 2886
Canterbury                          2673
Mount Druitt                        2460
Ku-ring-gai                         2290
Chatswood - Lane Cove               2241
Auburn                              2166
Pennant Hills - Epping              1888
Eastern Suburbs - North             1870
Fairfield                           1863
Warringah                           1815
Name: count, dtype: int64


Column: SA4_CODE21
Type: int64
Top 20 most frequent values:
SA4_CODE21
117    12018
121    11992
119    11761
125    11600
120     7359
127     6210
116     4946
126     4774
124     3563
122     2784
118     2623
115     2135
128     2053
123     1793
Name: count, dtype: int64


Column: SA4_NAME21
Type: object
Top 20 most frequent values:
SA4_NAME21
Sydney - City and Inner South             12018
Sydney - North Sydney and Hornsby         11992
Sydney - Inner South West                 11761
Sydney - Parramatta                       11600
Sydney - Inner West                        7359
Sydney - South West                        6210
Sydney - Blacktown                         4946
Sydney - Ryde                              4774
Sydney - Outer West and Blue Mountains     3563
Sydney - Northern Beaches                  2784
Sydney - Eastern Suburbs                   2623
Sydney - Baulkham Hills and Hawkesbury     2135
Sydney - Sutherland                        2053
Sydney - Outer South West                  1793
Name: count, dtype: int64


Column: AREASQKM21
Type: float64
Top 20 most frequent values:
AREASQKM21
3.2122     2518
1.9142     2127
81.7548    1821
5.6086     1550
13.2936    1542
8.9106     1402
4.3130     1289
29.8693    1270
3.6039     1179
1.3881     1076
3.7250     1041
3.8432     1035
3.9355      998
9.9882      924
14.4902     911

1_Area
3.2122     2518
1.9142     2127
81.7548    1821
5.6086     1550
13.2936    1542
8.9106     1402
4.3130     1289
29.8693    1270
3.6039     1179
1.3881     1076
3.7250     1041
3.8432     1035
3.9355      998
9.9882      924
14.4902     911
3.9101      833
7.0720      799
6.4036      777
3.3909      774
10.2515     760
Name: count, dtype: int64


Column: 2_ML
Type: float64
Top 20 most frequent values:
2_ML
0.000000     28698
34.171878     2518
26.802372     2127
34.776168     1821
14.009320     1550
32.246711     1542
11.070945     1402
34.923457     1289
53.942509     1270
3.969655      1179
10.502698     1076
7.058585      1041
16.727619     1035
9.698544       998
18.647592      924
14.353697      911
23.683342      799
7.189455       777
31.799411      774
7.158851       746
Name: count, dtype: int64


Column: 3_TRL
Type: float64
Top 20 most frequent values:
3_TRL
0.000000     23791
0.209249      2127
4.920704      1550
8.952339      1542
1.976420      1402
3.138923      1289
5.195971      1270
8.689532      1179
2.481691      1076
14.536661     1035
8.941532       998
7.487426       924
10.022339      911
6.459979       833
9.960382       799
14.745657      777
2.791655       774
16.895499      760
2.097842       745
8.005550       735
Name: count, dtype: int64


Column: 4_PRL
Type: float64
Top 20 most frequent values:
4_PRL
0.000000     12114
2.355749      2518
5.460735      2127
23.994276     1821
6.822032      1550
7.362372      1542
17.165086     1402
4.358145      1289
4.010589      1270
2.852222      1179
0.498938      1076
12.921691     1041
0.016410       998
1.433834       924
4.738756       911
0.329723       799
1.193868       774
2.769022       760
15.885392      746
7.903368       745
Name: count, dtype: int64


Column: 5_SRL
Type: float64
Top 20 most frequent values:
5_SRL
0.000000     6957
6.678012     2518
1.953894     2127
7.860223     1550
2.310562     1542
1.501439     1289
8.485141     1270
3.064664     1179
2.038320     1076
4.968148     1041
3.585528     1035
1.416884      998
5.374095      924
4.970993      911
5.649951      833
4.943749      799
10.141134     777
2.513120      774
0.800176      760
3.114614      746
Name: count, dtype: int64


Column: 6_TrRL
Type: float64
Top 20 most frequent values:
6_TrRL
11.009615    2518
4.802336     2127
3.445904     1821
7.342863     1550
5.986376     1542
4.876993     1402
3.801463     1289
15.245359    1270
2.431615     1179
1.267512     1076
5.721989     1041
3.233405     1035
5.140331      998
3.225691      924
12.550066     911
0.062437      833
4.192281      799
5.680912      777
3.023858      774
9.299488      760
Name: count, dtype: int64


Column: 7_RRL
Type: float64
Top 20 most frequent values:
7_RRL
7.505059     2518
12.860302    2127
43.788934    1821
40.855881    1550
67.291924    1542
0.000000     1402
31.103881    1289
4.427393     1270
30.467536    1179
14.357636    1076
21.517297    1041
17.498733    1035
32.486126     998
60.325810     924
70.371563     911
33.855351     833
48.719445     799
46.992913     777
32.706618     774
61.157433     760
Name: count, dtype: int64


Column: 8_LsRL
Type: float64
Top 20 most frequent values:
8_LsRL
0.000000    59472
0.615814     2518
0.194666     2127
0.308033     1179
0.393921     1041
0.086931      924
0.083428      799
0.415295      777
1.216816      667
1.444845      640
0.096625      634
0.499148      572
0.397452      550
0.228591      547
0.105176      539
0.047706      511
0.063458      478
0.177886      470
0.804736      440
1.044424      412
Name: count, dtype: int64


Column: 9_URL
Type: float64
Top 20 most frequent values:
9_URL
0.000000     13185
9.236466      2518
3.361680      2127
0.286764      1821
6.192691      1550
1.074018      1542
3.141233      1402
2.714130      1289
31.189607     1270
2.956881      1179
2.159705      1041
1.273885      1035
0.512046       998
0.958115       924
4.173559       911
0.267903       833
0.241861       799
2.505129       777
3.525824       746
0.739679       745
Name: count, dtype: int64


Column: 10_ToRL
Type: float64
Top 20 most frequent values:
10_ToRL
71.572593     2518
55.645234     2127
106.292046    1821
88.003714     1550
125.224302    1542
38.230677     1402
81.541438     1289
122.496569    1270
54.740138     1179
31.146795     1076
54.741336     1041
56.855831     1035
58.211873      998
97.539494      924
121.180973     911
46.295621      833
92.154211      799
87.670495      777
74.028530      774
90.921618      760
Name: count, dtype: int64


Column: 11_EoR
Type: float64
Top 20 most frequent values:
11_EoR
0.658489    2518
0.633019    2127
0.518541    1821
0.702689    1550
0.563783    1542
0.581767    1402
0.583030    1289
0.660019    1270
0.629302    1179
0.564609    1076
0.690019    1041
0.648736    1035
0.547443     998
0.519718     924
0.600655     911
0.347041     833
0.549916     799
0.604948     777
0.503572     774
0.417208     760
Name: count, dtype: int64


Column: 12_NoN
Type: int64
Top 20 most frequent values:
12_NoN
254    2539
278    2518
328    1949
325    1684
460    1678
447    1550
103    1443
317    1408
310    1300
266    1244
454    1209
367    1201
217    1141
120    1076
356    1041
232    1036
494    1005
365    1001
274     944
456     924
Name: count, dtype: int64


Column: 13_NDEs
Type: int64
Top 20 most frequent values:
13_NDEs
40     3671
18     3150
45     3085
48     2405
115    2337
43     2296
54     1880
19     1824
116    1821
51     1784
25     1635
7      1588
38     1476
39     1455
46     1451
4      1415
184    1213
21     1204
34     1203
20     1125
Name: count, dtype: int64


Column: 14_NNC2L
Type: int64
Top 20 most frequent values:
14_NNC2L
0     13238
5     11935
3      8864
2      7959
4      7856
6      7684
7      7317
1      7279
8      3954
9      3209
13     2653
10     1615
11     1429
45      198
15      170
18      167
12       84
Name: count, dtype: int64


Column: 15_NNC3L
Type: int64
Top 20 most frequent values:
15_NNC3L
176    3589
186    2518
296    2469
188    2388
202    2323
217    2044
325    1550
85     1404
263    1402
163    1344
227    1289
81     1139
105    1109
256    1079
251    1041
169    1013
155     948
211     929
320     924
330     917
Name: count, dtype: int64


Column: 16_NNC4L
Type: int64
Top 20 most frequent values:
16_NNC4L
29    5194
28    5016
10    3670
31    3483
41    3345
19    2884
54    2724
36    2634
34    2606
44    2555
30    2460
23    2359
47    2155
42    1993
25    1920
43    1821
26    1782
64    1743
17    1485
11    1484
Name: count, dtype: int64


Column: 17_AND
Type: float64
Top 20 most frequent values:
17_AND
3.071942    2518
2.787402    2127
2.323171    1821
2.899329    1550
2.597826    1542
3.048544    1402
2.800000    1289
2.825806    1270
3.083333    1198
2.833787    1179
2.910112    1041
2.990783    1035
2.804511     998
2.578947     924
2.797227     911
2.991228     833
2.524291     799
3.016667     777
2.662461     774
2.715859     760
Name: count, dtype: int64


Column: 18_NE
Type: int64
Top 20 most frequent values:
18_NE
678    2836
465    2611
384    2127
381    1821
641    1559
627    1542
177    1402
484    1289
477    1270
372    1224
539    1179
450    1145
204    1076
562    1041
356    1035
547    1022
402     998
374     956
605     924
819     911
Name: count, dtype: int64


Column: 19_MCI
Type: float64
Top 20 most frequent values:
19_MCI
0.341198    2518
0.260437    2127
0.082949    1821
0.260967    1550
0.183607    1542
0.373134    1402
0.248062    1289
0.273171    1270
0.237311    1179
0.361702    1076
0.292786    1041
0.326340    1035
0.259962     998
0.165380     924
0.211488     911
0.325942     833
0.150560     799
0.310180     777
0.222576     774
0.208195     760
Name: count, dtype: int64


Column: 20_CoI
Type: float64
Top 20 most frequent values:
20_CoI
0.001288    2518
0.001727    2127
0.002266    1821
0.000974    1550
0.001172    1542
0.003306    1402
0.001390    1289
0.001365    1270
0.001266    1179
0.002898    1076
0.001129    1041
0.001717    1035
0.001650     998
0.001248     924
0.000861     911
0.001634     833
0.001204     799
0.000915     777
0.001528     774
0.001107     760
Name: count, dtype: int64


Column: 21 NBS
Type: int64
Top 20 most frequent values:
21 NBS
179    2640
121    2436
239    2094
77     2003
195    1821
216    1656
13     1402
210    1362
86     1348
129    1318
85     1289
90     1273
134    1270
69     1241
60     1190
181    1159
208    1157
122    1133
149    1083
59     1076
Name: count, dtype: int64


Column: 22_CA
Type: float64
Top 20 most frequent values:
22_CA
0.0000     6783
1.7114     2518
0.2657     2127
0.0916     1821
0.8437     1550
0.2145     1542
2.5829     1402
0.1589     1289
11.2626    1270
0.1252     1179
0.1779     1158
0.1662     1076
0.7376     1041
0.2593     1035
0.1010      998
0.1266      936
0.1757      924
0.3947      911
0.1512      799
0.2552      777
Name: count, dtype: int64


Column: 23_EA
Type: float64
Top 20 most frequent values:
23_EA
0.0000    5208
0.0448    2939
0.2373    2127
0.1620    1821
0.1512    1550
0.3761    1542
0.0681    1298
0.1234    1179
0.0198    1076
0.1094    1041
0.0531    1035
0.1006     998
0.2763     924
0.1913     911
0.2349     833
0.1704     799
0.4078     777
0.0954     774
0.3820     760
0.0834     746
Name: count, dtype: int64


Column: 24_HA
Type: float64
Top 20 most frequent values:
24_HA
0.0000    54367
0.0141     2518
0.6055     1179
0.0198     1041
0.0236      998
0.0099      924
0.0080      783
0.0802      777
0.0143      762
0.0238      745
0.0496      735
0.2215      667
0.6732      653
0.0327      640
0.4614      634
0.0609      628
0.1011      610
0.0265      586
0.3842      544
0.0040      512
Name: count, dtype: int64


Column: 25_IA
Type: float64
Top 20 most frequent values:
25_IA
0.0000    45760
0.1692     1550
0.2091     1289
7.0192     1270
0.4633     1179
0.8485     1035
0.2427      924
3.3610      911
1.5921      777
0.7949      746
1.1277      735
1.1623      704
0.0158      667
0.0749      653
1.0121      638
0.9894      634
0.1085      628
2.2111      610
1.1046      603
0.4424      573
Name: count, dtype: int64


Column: 26_OA
Type: float64
Top 20 most frequent values:
26_OA
0.0000      76901
0.5809        799
3.0905        610
36.9622       572
1.2847        529
4.5556        524
0.2685        511
0.0188        470
0.6054        440
29.8461       333
1.5068        287
0.5316        277
236.3072      250
0.5203        250
0.3233        246
0.0894        182
1.1969        171
0.2402        170
0.0290        169
0.5723        167
Name: count, dtype: int64


Column: 27_PA
Type: float64
Top 20 most frequent values:
27_PA
0.0000     3088
0.9377     2518
0.2645     2127
75.9634    1821
0.4659     1550
4.6254     1542
1.3347     1289
6.5412     1270
0.2949     1179
0.1411     1076
1.4453     1041
0.3627     1035
0.2426      998
3.1635      924
3.3989      911
0.9175      833
1.7706      799
0.4574      777
0.3322      774
2.5370      760
Name: count, dtype: int64


Column: 28_PrA
Type: float64
Top 20 most frequent values:
28_PrA
0.0000     81132
89.0452      572
24.8536      529
0.4414       287
1.9033       277
8.3404       250
0.2423       250
38.0470      226
4.0613       167
0.6664       162
38.4243      154
1.0615       149
9.7696       149
95.6961      131
0.6855       127
0.8166       117
7.3069       108
25.9123      101
0.8194       101
33.4448       94
Name: count, dtype: int64


Column: 29_RA
Type: float64
Top 20 most frequent values:
29_RA
0.3973    2518
0.8655    2127
5.2913    1821
3.9786    1550
8.0776    1542
2.4530    1289
1.6484    1179
0.9371    1076
1.3995    1041
1.8993    1035
3.1727     998
6.1201     924
6.4029     911
2.6773     833
4.1134     799
3.3987     777
2.8152     774
7.0908     760
1.6856     746
4.0106     745
Name: count, dtype: int64


Column: 30_TA
Type: float64
Top 20 most frequent values:
30_TA
0.0000    45765
0.1069     2518
0.2812     2414
0.2465     1821
6.3277     1402
0.0892     1289
0.3432     1179
0.0230     1162
0.1239     1076
0.0061     1041
0.4203     1035
0.2950      998
0.0804      833
0.2855      799
0.2122      777
0.0135      774
0.1117      746
0.3275      735
0.0792      704
0.0862      667
Name: count, dtype: int64


Column: 31_WbA
Type: float64
Top 20 most frequent values:
31_WbA
0.0000    76282
5.0463     1270
0.0073     1041
0.7414      911
0.0837      667
0.1854      636
0.3204      628
0.2571      572
0.0300      440
0.0770      370
0.0761      361
0.0179      258
0.0055      238
1.1430      227
0.0719      218
0.0977      196
0.0112      173
0.0536      170
0.7259      130
0.0990      127
Name: count, dtype: int64


Column: 32_EoLU
Type: float64
Top 20 most frequent values:
32_EoLU
0.499465    2518
0.628441    2127
0.122861    1821
0.407475    1550
0.363720    1542
0.261460    1402
0.476854    1289
0.582427    1270
0.687141    1179
0.446482    1076
0.525484    1041
0.602666    1035
0.329226     998
0.404666     924
0.585135     911
0.368417     833
0.507587     799
0.582960     777
0.278621     774
0.352429     760
Name: count, dtype: int64


Column: 33_TP
Type: int64
Top 20 most frequent values:
33_TP
8001     2518
12452    2127
11779    1821
23257    1550
21731    1542
11       1402
16565    1289
4        1270
13814    1179
9854     1076
14827    1041
20797    1035
21564     998
19149     924
20807     911
9261      833
20271     802
16587     799
21213     777
13789     774
Name: count, dtype: int64


Column: 34_PD0MV
Type: float64
Top 20 most frequent values:
34_PD0MV
0.000000     2999
51.175073    2518
27.050143    2127
3.340030     1821
16.276329    1550
4.697707     1542
12.115666    1289
12.272482    1179
24.329055    1076
21.416395    1041
15.076387    1035
13.219616     998
4.238368      924
3.644041      911
6.296427      833
6.993865      799
14.065128     777
12.941425     774
3.223483      760
20.092988     746
Name: count, dtype: int64


Column: 35_PD1MV
Type: float64
Top 20 most frequent values:
35_PD1MV
37.523105     2518
54.502767     2127
31.416374     1821
0.000000      1620
42.421564     1550
35.830438     1542
100.000000    1315
47.456076     1289
53.126689     1179
53.529755     1076
53.881915     1041
57.116055     1035
56.830135      998
35.070108      924
27.416328      911
29.784224      833
31.063395      799
43.724201      777
41.657856      774
30.343958      760
Name: count, dtype: int64


Column: 36_PD2MV
Type: float64
Top 20 most frequent values:
36_PD2MV
0.000000     2872
9.638236     2518
15.680027    2127
41.511803    1821
27.249963    1550
41.987491    1542
27.287701    1289
29.014237    1179
17.065344    1076
19.990702    1041
22.393460    1035
22.857143     998
43.116635     924
44.103847     911
37.424832     833
37.689162     799
29.521480     777
30.809896     774
45.975149     760
22.970596     746
Name: count, dtype: int64


Column: 37_PD3MV
Type: float64
Top 20 most frequent values:
37_PD3MV
0.000000     3062
1.188276     2518
1.861479     2127
14.992466    1821
8.867285     1550
11.994441    1542
8.437042     1289
4.271040     1179
3.588098     1076
3.378274     1041
3.765746     1035
4.804549      998
12.014022     924
15.514545     911
16.660771     833
15.685072     799
8.882434      777
9.558046      774
14.280569     760
4.687107      746
Name: count, dtype: int64


Column: 38_PD≥4MV
Type: float64
Top 20 most frequent values:
38_PD≥4MV
0.000000    3062
0.475310    2518
0.905584    2127
8.739327    1821
5.184858    1550
5.489924    1542
4.703514    1289
1.315552    1179
1.487748    1076
1.332713    1041
1.648352    1035
2.288557     998
5.560867     924
9.321239     911
9.833746     833
8.568507     799
3.806757     777
5.032776     774
6.176841     760
1.859764     746
Name: count, dtype: int64


Column: 39_PUE
Type: float64
Top 20 most frequent values:
39_PUE
0.000000     2999
7.224097     2518
6.593318     2127
7.428474     1821
10.538763    1550
8.872118     1542
8.626622     1289
5.595772     1179
9.711792     1076
5.260673     1041
9.597538     1035
9.956409      998
8.287639      924
9.025809      911
11.553828     833
10.459999     799
11.172394     777
10.298064     774
9.985478      760
9.123766      746
Name: count, dtype: int64


Column: 40_AMI
Type: int64
Top 20 most frequent values:
40_AMI
1979    2518
2048    2127
906     2059
1388    1956
1557    1542
2450    1402
1189    1289
1125    1270
1934    1179
1174    1076
2050    1041
1217    1035
1302     998
1054     956
1493     924
1501     921
1166     911
1238     882
992      799
1029     777
Name: count, dtype: int64


Column: 41_NPTtWbyPT
Type: int64
Top 20 most frequent values:
41_NPTtWbyPT
352     3156
0       3133
486     2127
161     1871
422     1842
151     1821
232     1723
1461    1550
708     1471
714     1289
424     1041
1565    1035
902      998
107      950
200      927
351      924
347      850
204      833
188      799
1306     777
Name: count, dtype: int64


Column: 42_NPTtWbyTx
Type: int64
Top 20 most frequent values:
42_NPTtWbyTx
0     14638
9      6737
6      5568
12     5277
4      4775
22     4227
3      3709
10     3622
8      3433
11     3350
7      3249
19     2645
18     2634
17     2336
15     2200
13     1974
14     1770
20     1749
5      1660
23     1155
Name: count, dtype: int64


Column: 43_NPTtWbyCD
Type: int64
Top 20 most frequent values:
43_NPTtWbyCD
0       2941
400     2518
1005    2127
2149    1821
2874    1550
2902    1542
2409    1289
1516    1179
2723    1141
1251    1076
1295    1041
3143    1035
2707     998
2728     924
3491     911
2899     867
1738     836
2971     777
1918     774
2182     760
Name: count, dtype: int64


Column: 44_NPTtWbyCP
Type: int64
Top 20 most frequent values:
44_NPTtWbyCP
112    3129
0      3062
42     2672
120    2054
161    2038
111    1977
224    1784
309    1781
181    1773
121    1711
350    1550
248    1423
175    1396
95     1343
192    1211
191    1191
203    1169
157    1104
240    1064
291     998
Name: count, dtype: int64


Column: 45_NPTtWbyO
Type: int64
Top 20 most frequent values:
45_NPTtWbyO
832    2518
571    2127
166    1821
232    1758
298    1550
282    1542
0      1533
4      1402
159    1383
572    1325
269    1289
229    1192
422    1179
233    1126
210    1119
871    1041
486    1035
514    1033
311     998
155     997
Name: count, dtype: int64


Column: 46_NPWfH
Type: int64
Top 20 most frequent values:
46_NPWfH
2651    2518
4715    2185
2629    1821
0       1597
1969    1550
5386    1542
4       1465
2718    1289
4512    1179
1946    1076
5293    1041
4022    1035
4379     998
4801     924
3131     911
1771     833
1809     799
3885     797
2728     777
2078     774
Name: count, dtype: int64


Column: 47_PWCJH
Type: float64
Top 20 most frequent values:
47_PWCJH
88.957055     2518
92.102797     2127
84.397511     1821
0.000000      1584
66.512308     1550
88.021691     1542
100.000000    1465
76.548251     1289
89.725304     1179
72.915794     1076
90.822677     1041
75.809311     1035
78.956666      998
87.312560      924
77.477992      911
86.262489      833
71.803653      799
72.840458      777
76.909189      774
89.464221      760
Name: count, dtype: int64


Column: 48_PBCJH
Type: float64
Top 20 most frequent values:
48_PBCJH
0.000000     3049
11.042945    2518
7.897203     2127
15.602489    1821
33.487692    1550
11.978309    1542
23.451749    1289
10.274696    1179
27.084206    1076
9.177323     1041
24.190689    1035
21.043334     998
12.687440     924
22.522008     911
13.737511     833
28.196347     799
27.159542     777
23.090811     774
10.535778     760
21.719193     746
Name: count, dtype: int64


Column: 49_ANP_FH
Type: float64
Top 20 most frequent values:
49_ANP_FH
2.398084    2518
2.501050    2127
3.261237    1821
0.000000    1652
3.542721    1550
3.281978    1542
2.000000    1397
3.238119    1289
2.902793    1179
3.099436    1076
2.748919    1041
3.028439    1035
3.248887     998
3.293622     924
3.428651     911
3.429858     833
3.558714     799
3.366091     777
3.298151     774

In [33]:
pd.options.display.max_columns = None

In [34]:
display(df.head(1))

,Incident ID,Main_Category,Longitude,Latitude,Start_Time,Last_Updated,Day,End_Time,Duration_in_Minutes,Primary_Vehicle,Secondary_Vehicle,Attending_Groups,Display_Name,Is_Major_Incident,Diversions,Advice_A,Advice_B,Other_Advice,Closure_Type,Direction,Main_Street,Affected_Lanes,Actual_Number_of_Lanes,Suburb,Traffic_Volume,SA2_CODE21,SA2_NAME21,SA3_CODE21,SA3_NAME21,SA4_CODE21,SA4_NAME21,AREASQKM21,LOCI_URI21,0_ZID,1_Area,2_ML,3_TRL,4_PRL,5_SRL,6_TrRL,7_RRL,8_LsRL,9_URL,10_ToRL,11_EoR,12_NoN,13_NDEs,14_NNC2L,15_NNC3L,16_NNC4L,17_AND,18_NE,19_MCI,20_CoI,21 NBS,22_CA,23_EA,24_HA,25_IA,26_OA,27_PA,28_PrA,29_RA,30_TA,31_WbA,32_EoLU,33_TP,34_PD0MV,35_PD1MV,36_PD2MV,37_PD3MV,38_PD≥4MV,39_PUE,40_AMI,41_NPTtWbyPT,42_NPTtWbyTx,43_NPTtWbyCD,44_NPTtWbyCP,45_NPTtWbyO,46_NPWfH,47_PWCJH,48_PBCJH,49_ANP_FH
0,1,Crash,151.058,-33.9431,14-08-2018 19:21,14-08-2018 20:00,Tuesday,14-08-2018 20:00,39.31995,Car,Car,['Emergency services'],accident 2 cars,False,unknown,Exercise caution,Allow extra travel time,unknown,Affected,Eastbound,M5 Motorway,99,99,Riverwood,Unknown,119021366,Punchbowl,11902,Canterbury,119,Sydney - Inner South West,5.2458,http://linked.data.gov.au/dataset/asgsed3/SA2/...,119021366,5.2458,7.488104,3.03878,2.236683,6.602571,2.551265,42.10309,0.0,0.115587,64.13608,0.504771,325,40,7,260,17,2.790769,491,0.258915,0.001351,210,0.0938,0.1211,0.0,0.7056,0.0,0.5171,0.0,3.8082,0.0,0.0,0.386385,21537,11.297837,37.886855,30.565724,12.296173,7.953411,12.109393,831,342,16,2806,276,260,1520,67.63446,32.36554,3.713468

In [35]:
import pandas as pd

# Assuming 'Start_Time' is the column with the dates you want to filter by,
# and it's in the format 'dd-mm-yyyy HH:MM'
df['Start_Time'] = pd.to_datetime(df['Start_Time'], format='%d-%m-%Y %H:%M')

# Define your start and end dates
start_date = '2020-03-10'
end_date = '2022-10-14'

# Convert your start and end dates to datetime
start_date = pd.to_datetime(start_date)
end_date = pd.to_datetime(end_date)

# Filter the DataFrame to include only the rows between your start and end dates
subset_df = df[(df['Start_Time'] >= start_date) & (df['Start_Time'] <= end_date)]

# Display the first row of the filtered DataFrame as a test
display(subset_df.head(1))

,Incident ID,Main_Category,Longitude,Latitude,Start_Time,Last_Updated,Day,End_Time,Duration_in_Minutes,Primary_Vehicle,Secondary_Vehicle,Attending_Groups,Display_Name,Is_Major_Incident,Diversions,Advice_A,Advice_B,Other_Advice,Closure_Type,Direction,Main_Street,Affected_Lanes,Actual_Number_of_Lanes,Suburb,Traffic_Volume,SA2_CODE21,SA2_NAME21,SA3_CODE21,SA3_NAME21,SA4_CODE21,SA4_NAME21,AREASQKM21,LOCI_URI21,0_ZID,1_Area,2_ML,3_TRL,4_PRL,5_SRL,6_TrRL,7_RRL,8_LsRL,9_URL,10_ToRL,11_EoR,12_NoN,13_NDEs,14_NNC2L,15_NNC3L,16_NNC4L,17_AND,18_NE,19_MCI,20_CoI,21 NBS,22_CA,23_EA,24_HA,25_IA,26_OA,27_PA,28_PrA,29_RA,30_TA,31_WbA,32_EoLU,33_TP,34_PD0MV,35_PD1MV,36_PD2MV,37_PD3MV,38_PD≥4MV,39_PUE,40_AMI,41_NPTtWbyPT,42_NPTtWbyTx,43_NPTtWbyCD,44_NPTtWbyCP,45_NPTtWbyO,46_NPWfH,47_PWCJH,48_PBCJH,49_ANP_FH
25314,25315,Crash,151.073,-33.9436,2020-03-10 00:52:00,10-03-2020 01:02,Tuesday,10-03-2020 01:02,10.336717,Car,Car,"['Emergency services', 'Motorway Crew']",crash 2 cars,False,unknown,Expect delays,Exercise caution,unknown,Affected,Eastbound,M5 Motorway,1,3,Beverly Hills,Heavy,119031370,Narwee - Beverly Hills,11903,Hurstville,119,Sydney - Inner South West,3.3909,http://linked.data.gov.au/dataset/asgsed3/SA2/...,119031370,3.3909,31.799411,2.791655,1.193868,2.51312,3.023858,32.706618,0.0,0.0,74.02853,0.503572,317,66,5,217,28,2.662461,456,0.222576,0.001528,132,0.1266,0.0954,0.008,0.0,0.0,0.3322,0.0,2.8152,0.0135,0.0,0.278621,13789,12.941425,41.657856,30.809896,9.558046,5.032776,10.298064,1054,357,10,1918,153,121,2078,76.909189,23.090811,3.298151

In [36]:
subset_df

,Incident ID,Main_Category,Longitude,Latitude,Start_Time,Last_Updated,Day,End_Time,Duration_in_Minutes,Primary_Vehicle,Secondary_Vehicle,Attending_Groups,Display_Name,Is_Major_Incident,Diversions,Advice_A,Advice_B,Other_Advice,Closure_Type,Direction,Main_Street,Affected_Lanes,Actual_Number_of_Lanes,Suburb,Traffic_Volume,SA2_CODE21,SA2_NAME21,SA3_CODE21,SA3_NAME21,SA4_CODE21,SA4_NAME21,AREASQKM21,LOCI_URI21,0_ZID,1_Area,2_ML,3_TRL,4_PRL,5_SRL,6_TrRL,7_RRL,8_LsRL,9_URL,10_ToRL,11_EoR,12_NoN,13_NDEs,14_NNC2L,15_NNC3L,16_NNC4L,17_AND,18_NE,19_MCI,20_CoI,21 NBS,22_CA,23_EA,24_HA,25_IA,26_OA,27_PA,28_PrA,29_RA,30_TA,31_WbA,32_EoLU,33_TP,34_PD0MV,35_PD1MV,36_PD2MV,37_PD3MV,38_PD≥4MV,39_PUE,40_AMI,41_NPTtWbyPT,42_NPTtWbyTx,43_NPTtWbyCD,44_NPTtWbyCP,45_NPTtWbyO,46_NPWfH,47_PWCJH,48_PBCJH,49_ANP_FH
25314,25315,Crash,151.073000,-33.943600,2020-03-10 00:52:00,10-03-2020 01:02,Tuesday,10-03-2020 01:02,10.336717,Car,Car,"['Emergency services', 'Motorway Crew']",crash 2 cars,False,unknown,Expect delays,Exercise caution,unknown,Affected,Eastbound,M5 Motorway,1,3,Beverly Hills,Heavy,119031370,Narwee - Beverly Hills,11903,Hurstville,119,Sydney - Inner South West,3.3909,http://linked.data.gov.au/dataset/asgsed3/SA2/...,119031370,3.3909,31.799411,2.791655,1.193868,2.513120,3.023858,32.706618,0.000000,0.000000,74.028530,0.503572,317,66,5,217,28,2.662461,456,0.222576,0.001528,132,0.1266,0.0954,0.0080,0.0000,0.0000,0.3322,0.0000,2.8152,0.0135,0.0000,0.278621,13789,12.941425,41.657856,30.809896,9.558046,5.032776,10.298064,1054,357,10,1918,153,121,2078,76.909189,23.090811,3.298151
25315,25316,Crash,150.733000,-33.662100,2020-03-10 01:12:00,10-03-2020 03:04,Tuesday,10-03-2020 03:04,111.495000,Car,Car,"['Emergency services', 'Transport for NSW']","crash car, horse",False,unknown,Reduced speed limit,"Allow extra travel time, Exercise caution",unknown,Affected,Both directions,Londonderry Road,99,99,Londonderry,Unknown,124041468,Yarramundi - Londonderry,12404,Richmond - Windsor,124,Sydney - Outer West and Blue Mountains,81.4358,http://linked.data.gov.au/dataset/asgsed3/SA2/...,124041468,81.4358,0.000000,8.155625,24.826691,12.917728,5.516486,91.283925,0.000000,14.695506,157.395961,0.566615,180,46,0,124,10,2.544444,248,0.194366,0.002938,107,0.0000,0.0355,0.0000,0.0000,30.9463,15.2258,25.9123,9.3159,0.0000,0.0000,0.563257,7507,1.889939,17.287382,28.793774,21.901056,30.127849,6.314107,1106,18,0,1568,84,319,723,70.077220,29.922780,3.560182
25316,25317,Crash,150.930000,-33.806900,2020-03-10 01:20:00,10-03-2020 02:32,Tuesday,10-03-2020 02:32,71.303450,Multiple vehicles,Multiple vehicles,unknown,crash multiple vehicles,False,unknown,Allow extra travel time,Exercise caution,unknown,Affected,Westbound,M4 Mwy,99,99,Greystanes,Heavy,125041588,Pendle Hill - Girraween,12504,Parramatta,125,Sydney - Parramatta,4.4615,http://linked.data.gov.au/dataset/asgsed3/SA2/...,125041588,4.4615,11.346077,8.005550,0.000000,2.544279,6.255510,28.119736,0.000000,0.099430,56.370582,0.582721,224,43,4,158,19,2.683036,320,0.218962,0.002194,129,0.0382,0.1327,0.0496,1.1277,0.0000,0.1245,0.0000,2.6613,0.3275,0.0000,0.496286,13946,10.499537,46.299722,31.706753,7.816836,3.677151,9.780582,1200,412,9,2015,181,186,2335,76.135969,23.864031,3.404193
25317,25318,Breakdown,150.854000,-33.988500,2020-03-10 01:29:00,10-03-2020 01:40,Tuesday,10-03-2020 01:40,11.130333,Car,NaN,['Emergency services'],breakdown car,False,unknown,Allow extra travel time,Exercise caution,unknown,Lanes closed,Northbound,Hume Motorway,1,99,Ingleburn,Unknown,123021705,Ingleburn,12302,Campbelltown (NSW),123,Sydney - Outer South West,14.1156,http://linked.data.gov.au/dataset/asgsed3/SA2/...,123021705,14.1156,19.149198,0.000000,1.881725,16.752241,17.857418,48.865260,0.000000,4.279408,108.785250,0.628618,634,170,1,438,25,2.501577,809,0.139351,0.000970,208,0.0998,0.1551,0.0000,4.5629,1.5068,2.0981,0.4414,4.9703,0.2812,0.0000,0.662602,16714,8.904736,40.756994,34.009874,10.788078,5.540318,10.207012,1034,552,18,2933,255,232,1992,69.249639,30.750361,3.336699
25318,25319,Breakdown,151.202000,-33.773900,2020-03-10 01:37:00,10-03-2020 02:33,Tuesday,10-03-2020 02:33,56.273950,Car,NaN,"['Emergency services', 'Transport for NSW']",breakdown car,False,unknown,Reduce your speed,Exercise caution,unknown,Lanes closed,City bound,Warringah,1,2,Roseville,Unknown,121031408,Lindfield - Roseville,12103,Ku-ring-gai,121,Sydney - North Sydney and Hornsby,11.8765,http://linked.data.gov.au/dataset/asgsed3/SA2/...,121031408,11.8765,0.000000,12.937471,0.778029,2.715345,8.536902,83.929272,0.038003,1.376357,110.311379,0.365207,492,84,5,358,44,2.741870,704,0.217569,0.000994,338,0.3640,0.2667,0.0082,0.0000,0.0000,2.6337,0.0000,8.6039,0.0000,0.0000,0.332069,24604,6.069748,39.230119,39.049113,10.860384,4.790636,9.600065,1783,536,12,2723,214,307,6594,89.421003,10.578997,3.273987
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85188,85189,Crash,150.653270,-33.754089,2022-07-19 10:00:00,19-07-2022 10:00,Tuesday,UNKNOWN,0.000500,Car,Unknown,"['Emergency services', 'Transport for NSW']",CRASH Car,False,NaN,Exercise caution,Allow extra travel time,Traffic signals are flashing yellow at the\nin...,Affected,All directions,Great Western Hwy,99,99,Emu Plains,Unknown,124031459,Emu Plains - Leonay,12403,Penrith,124,Sydney - Outer West and Blue Mountains,13.7940,http://linked.data.gov.au/dataset/asgsed3/SA2/...,124031459,13.7940,8.398488,5.289526,0.000000,7.423731,6.035645,61.586725,0.194276,3.545744,92.474135,0.508495,458,107,4,311,36,2.602620,602,0.159166,0.001266,262,0.0580,0.3247,0.0000,2.3242,1.5969,2.2860,0.0000,6.4783,0.0000,0.7259,0.637855,13914,4.434500,30.349878,40.358015,15.561432,9.296176,6.540175,1245,114,0,3050,170,230,2223,78.330137,21.669863,3.163504
85189,85190,Breakdown,151.209896,-33.873316,2022-07-19 14:14:00,19-07-2022 14:15,Tuesday,UNKNOWN,0.300283,Car,Unknown,[' '],BREAKDOWN Car,False,NaN,NaN,NaN,NaN,Lanes closed,Northbound,Elizabeth Street,1,2,Sydney CBD,Unknown,117031644,Sydney (North) - Millers Point,11703,Sydney Inner City,117,Sydney - City and Inner South,3.2122,http://linked.data.gov.au/dataset/asgsed3/SA2/...,117031644,3.2122,34.171878,0.000000,2.355749,6.678012,11.009615,7.505059,0.615814,9.236466,71.572593,0.658489,278,18,13,186,54,3.071942,465,0.341198,0.001288,179,1.7114,0.0448,0.0141,0.0000,0.0000,0.9377,0.0000,0.3973,0.1069,0.0000,0.499465,8001,51.175073,37.523105,9.638236,1.188276,0.475310,7.224097,1979,352,9,400,42,832,2651,88.957055,11.042945,2.398084
85190,85191,Breakdown,151.173469,-33.945945,2022-07-22 01:32:00,22-07-2022 01:33,Friday,UNKNOWN,0.606333,Car,Unknown,['Transport for NSW'],BREAKDOWN Car,False,NaN,Exercise caution,NaN,NaN,Lanes closed,Northbound,General Holmes Drive,1,3,Mascot,Unknown,117011325,Sydney Airport,11701,Botany,117,Sydney - City and Inner South,8.9106,http://linked.data.gov.au/dataset/asgsed3/SA2/...,117011325,8.9106,11.070945,1.976420,17.165086,0.000000,4.876993,0.000000,0.000000,3.141233,38.230677,0.581767,103,4,2,85,10,3.048544,177,0.373134,0.003306,13,2.5829,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,NaN,6.3277,0.0000,0.261460,11,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2450,0,0,0,0,4,4,100.000000,0.000000,0.000000
85191,85192,Breakdown,151.215823,-33.699419,2022-07-26 03:11:00,26-07-2022 03:12,Tuesday,UNKNOWN,0.671500,Car,Unknown,"['Transport for NSW', 'Emergency services']",BREAKDOWN Car,False,NaN,Reduce your speed,Exercise caution,NaN,Lanes closed,Westbound,Mona Vale Road,1,2,Terrey Hills,Unknown,122031432,Terrey Hills - Duffys Forest,12203,Warringah,122,Sydney - Northern Beaches,70.5438,http://linked.data.gov.au/dataset/asgsed3/SA2/...,122031432,70.5438,0.000000,19.433616,8.295387,20.301886,3.812945,19.544761,0.000000,33.477063,104.865658,0.707505,188,44,7,121,12,2.606383,268,0.218329,0.002627,112,0.0357,0.1944,0.0000,0.0000,0.0000,59.3027,0.0000,9.8680,0.0000,1.1430,0.220597,3801,1.512605,20.840336,41.092437,19.159664,17.394958,6.866614,1500,19,0,686,32,72,733,82.852386,17.147614,3.310865
85192,85193,Breakdown,151.100915,-33.867989,2022-07-26 12:06:00,26-07-2022 12:07,Tuesday,UNKNOWN,0.843883,Truck,Unknown,['Motorway Crew'],BREAKDOWN Truck,False,NaN,Exercise caution,Allow extra travel time,NaN,Lanes closed,Westbound,M4 Motorway,1,1,Concord,Unknown,120011383,Concord - Mortlake - Cabarita,12001,Canada Bay,120,Sydney - Inner West,6.3199,http://linked.data.gov.au/dataset/asgsed3/SA2/...,120011383,6.3199,11.694934,1.595959,2.538014,5.788920,5.245300,57.289027,0.000000,0.115196,84.267350,0.470281,494,69,9,362,54,2.811741,717,0.227874,0.000962,181,0.0301,0.0920,0.0022,0.0000,0.0000,1.8417,0.0000,4.3539,0.0000,0.0000,0.306542,23109,6.787964,39.573128,38.336832,10.158619,5.143457,8.611364,1515,322,8,3959,269,344,5058,85.452759,14.547241,3.015410

In [37]:
import pandas as pd

# Ensure the 'Start_Time' column is in datetime format
df['Start_Time'] = pd.to_datetime(df['Start_Time'], format='%d-%m-%Y %H:%M')

# Define the cutoff date
cutoff_date = '2020-03-10'

# Convert the cutoff date to a datetime object
cutoff_date = pd.to_datetime(cutoff_date)

# Filter the DataFrame to only include rows before the cutoff date
subset_df_before = df[df['Start_Time'] < cutoff_date]

# Display the first row of the filtered DataFrame to verify
subset_df_before

,Incident ID,Main_Category,Longitude,Latitude,Start_Time,Last_Updated,Day,End_Time,Duration_in_Minutes,Primary_Vehicle,Secondary_Vehicle,Attending_Groups,Display_Name,Is_Major_Incident,Diversions,Advice_A,Advice_B,Other_Advice,Closure_Type,Direction,Main_Street,Affected_Lanes,Actual_Number_of_Lanes,Suburb,Traffic_Volume,SA2_CODE21,SA2_NAME21,SA3_CODE21,SA3_NAME21,SA4_CODE21,SA4_NAME21,AREASQKM21,LOCI_URI21,0_ZID,1_Area,2_ML,3_TRL,4_PRL,5_SRL,6_TrRL,7_RRL,8_LsRL,9_URL,10_ToRL,11_EoR,12_NoN,13_NDEs,14_NNC2L,15_NNC3L,16_NNC4L,17_AND,18_NE,19_MCI,20_CoI,21 NBS,22_CA,23_EA,24_HA,25_IA,26_OA,27_PA,28_PrA,29_RA,30_TA,31_WbA,32_EoLU,33_TP,34_PD0MV,35_PD1MV,36_PD2MV,37_PD3MV,38_PD≥4MV,39_PUE,40_AMI,41_NPTtWbyPT,42_NPTtWbyTx,43_NPTtWbyCD,44_NPTtWbyCP,45_NPTtWbyO,46_NPWfH,47_PWCJH,48_PBCJH,49_ANP_FH
0,1,Crash,151.058,-33.9431,2018-08-14 19:21:00,14-08-2018 20:00,Tuesday,14-08-2018 20:00,39.319950,Car,Car,['Emergency services'],accident 2 cars,False,unknown,Exercise caution,Allow extra travel time,unknown,Affected,Eastbound,M5 Motorway,99,99,Riverwood,Unknown,119021366,Punchbowl,11902,Canterbury,119,Sydney - Inner South West,5.2458,http://linked.data.gov.au/dataset/asgsed3/SA2/...,119021366,5.2458,7.488104,3.038780,2.236683,6.602571,2.551265,42.103090,0.000000,0.115587,64.136080,0.504771,325,40,7,260,17,2.790769,491,0.258915,0.001351,210,0.0938,0.1211,0.0000,0.7056,0.0,0.5171,0.0,3.8082,0.0000,0.0000,0.386385,21537,11.297837,37.886855,30.565724,12.296173,7.953411,12.109393,831,342,16,2806,276,260,1520,67.634460,32.365540,3.713468
1,2,Breakdown,151.159,-33.8096,2018-08-15 00:47:00,15-08-2018 00:59,Wednesday,15-08-2018 00:59,12.029000,Car,NaN,['Motorway Crew'],breakdown car,False,unknown,Exercise caution,NaN,unknown,Lanes closed,Westbound,Lane Cove Tunnel,1,2,Lane Cove North,Unknown,121011399,Chatswood (West) - Lane Cove North,12101,Chatswood - Lane Cove,121,Sydney - North Sydney and Hornsby,5.5372,http://linked.data.gov.au/dataset/asgsed3/SA2/...,121011399,5.5372,8.365015,2.097842,7.903368,4.617769,0.232704,40.351141,0.000000,0.739679,64.307518,0.515889,269,59,6,176,28,2.643123,383,0.215760,0.001839,210,0.0080,0.1223,0.0238,0.0000,0.0,1.3725,0.0,4.0106,0.0000,0.0000,0.302463,21270,10.253288,52.715538,29.067219,5.723332,2.240623,7.776211,1643,651,6,2652,227,514,6070,88.007396,11.992604,3.023239
2,3,Crash,150.875,-33.7344,2018-08-15 01:12:00,15-08-2018 01:29,Wednesday,15-08-2018 01:29,16.956667,Car,NaN,"['Emergency services', 'Motorway Crew']",accident car,False,unknown,NaN,NaN,unknown,Lanes closed,Westbound,Westlink M7 off-ramp,1,1,Quakers Hill,Unknown,116011304,Blacktown (North) - Marayong,11601,Blacktown,116,Sydney - Blacktown,7.3828,http://linked.data.gov.au/dataset/asgsed3/SA2/...,116011304,7.3828,9.051683,0.000000,12.307502,5.297219,9.525819,56.104489,0.000000,0.128916,92.415628,0.523895,468,112,2,307,47,2.617521,631,0.176155,0.001177,234,0.0000,0.2768,0.0000,0.3180,0.0,0.9027,0.0,5.6929,0.1924,0.0000,0.352217,20570,8.724832,41.000610,34.716290,10.600976,4.957291,9.688867,1030,532,18,3686,323,256,2398,67.554766,32.445234,3.341706
3,4,Crash,150.973,-33.8172,2018-08-15 01:27:00,15-08-2018 02:09,Wednesday,15-08-2018 02:09,42.804117,Truck,Car,"['Emergency services', 'Transport for NSW']",accident car,False,unknown,Exercise caution,Allow extra travel time,unknown,Affected,Westbound,M4 Motorway,1,1,South Wentworthville,Moderate,125041589,Wentworthville - Westmead,12504,Parramatta,125,Sydney - Parramatta,3.9355,http://linked.data.gov.au/dataset/asgsed3/SA2/...,125041589,3.9355,9.698544,8.941532,0.016410,1.416884,5.140331,32.486126,0.000000,0.512046,58.211873,0.547443,266,39,7,188,31,2.804511,402,0.259962,0.001650,174,0.1010,0.1006,0.0236,0.0000,0.0,0.2426,0.0,3.1727,0.2950,0.0000,0.329226,21564,13.219616,56.830135,22.857143,4.804549,2.288557,9.956409,1302,902,11,2707,291,311,4379,78.956666,21.043334,3.248887
4,5,Crash,150.981,-33.7919,2018-08-15 01:37:00,15-08-2018 02:18,Wednesday,15-08-2018 02:18,40.840000,Multiple vehicles,Multiple vehicles,['Tow Truck'],accident 3 vehicles,False,unknown,Exercise caution,NaN,unknown,Affected,Southbound,Old Windsor Road,99,99,Northmead,Unknown,125041493,Toongabbie - Constitution Hill,12504,Parramatta,125,Sydney - Parramatta,7.4795,http://linked.data.gov.au/dataset/asgsed3/SA2/...,125041493,7.4795,0.000000,9.092391,0.000000,7.092430,13.338771,51.982067,0.000000,4.266734,85.772393,0.515169,454,105,3,322,23,2.585903,598,0.160576,0.001272,194,0.4036,0.1788,0.0000,0.0000,0.0,0.8217,0.0,6.0754,0.0000,0.0000,0.285901,22840,8.134605,39.745628,35.466349,10.996290,5.657128,9.071804,1170,589,18,3487,314,261,3798,77.384802,22.615198,3.295874
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85606,85607,Breakdown,151.193,-33.8877,2018-08-14 08:09:00,14-08-2018 08:09,Tuesday,UNKNOWN,0.073550,Car,Unknown,"['RMS', 'Tow truck']",BREAKDOWN Car,False,NaN,NaN,NaN,NaN,Lanes closed,Westbound,Cleveland Street,99,99,Camperdown,Unknown,117031638,Camperdown - Darlington,11703,Sydney Inner City,117,Sydney - City and Inner South,1.7106,http://linked.data.gov.au/dataset/asgsed3/SA2/...,117031638,1.7106,0.000000,6.229383,0.770780,1.555551,2.349888,12.909696,0.974891,0.628599,25.418788,0.609042,156,17,5,105,29,2.935897,275,0.390879,0.002070,44,0.1061,0.7496,0.0680,0.0285,0.0,0.1834,0.0,0.5750,0.0000,0.0000,0.580342,8323,25.450139,53.116343,17.659280,2.770083,1.004155,8.626697,1457,347,10,726,68,587,2683,89.198132,10.801868,2.643437
85607,85608,Crash,151.054,-33.7991,2018-08-15 04:44:00,15-08-2018 04:44,Wednesday,UNKNOWN,0.000000,Unknown,Unknown,"['RMS', 'Tow truck']",ACCIDENT 2 cars,False,NaN,NaN,NaN,NaN,Lanes closed,Eastbound,Kissing Point Road,1,2,Dundas,Unknown,125021477,Ermington - Rydalmere,12502,Carlingford,125,Sydney - Parramatta,9.8655,http://linked.data.gov.au/dataset/asgsed3/SA2/...,125021477,9.8655,0.000000,21.451793,9.077881,1.305794,13.243906,62.631529,0.000000,5.247824,112.958727,0.560480,607,100,5,408,92,2.823723,881,0.227461,0.000783,293,1.8816,0.5680,0.0609,0.1085,0.0,1.3128,0.0,5.6133,0.0000,0.3204,0.548046,24612,8.555502,37.190984,37.869607,10.954920,5.428987,9.198765,1177,347,12,4061,298,276,4287,80.158441,19.841559,3.276092
85608,85609,Crash,151.066,-33.7527,2018-08-15 04:45:00,15-08-2018 04:45,Wednesday,UNKNOWN,0.000000,Multiple vehicles,Unknown,[],ACCIDENT 3 vehicles,False,NaN,Allow extra travel time,NaN,NaN,Affected,Southbound,Beecroft Road,99,99,Beecroft,Heavy,126011496,Pennant Hills - Cheltenham,12601,Pennant Hills - Epping,126,Sydney - Ryde,13.2936,http://linked.data.gov.au/dataset/asgsed3/SA2/...,126011496,13.2936,32.246711,8.952339,7.362372,2.310562,5.986376,67.291924,0.000000,1.074018,125.224302,0.563783,460,115,5,296,41,2.597826,627,0.183607,0.001172,216,0.2145,0.3761,0.0000,0.0000,0.0,4.6254,0.0,8.0776,0.0000,0.0000,0.363720,21731,4.697707,35.830438,41.987491,11.994441,5.489924,8.872118,1557,422,0,2902,224,282,5386,88.021691,11.978309,3.281978
85609,85610,Breakdown,151.154,-33.7587,2018-08-15 04:47:00,15-08-2018 04:47,Wednesday,UNKNOWN,0.000000,Truck,Unknown,['RMS'],BREAKDOWN Truck,False,NaN,Allow extra travel time,NaN,NaN,Lanes closed,Southbound,Pacific Highway,1,2,Gordon,Moderate,121031407,Gordon - Killara,12103,Ku-ring-gai,121,Sydney - North Sydney and Hornsby,11.6713,http://linked.data.gov.au/dataset/asgsed3/SA2/...,121031407,11.6713,0.000000,8.402822,0.000000,3.362577,9.581556,72.142489,0.000000,0.000000,93.489444,0.334247,412,81,0,289,41,2.711165,577,0.202686,0.001240,220,0.1110,0.1334,0.0000,0.0000,0.0,3.6925,0.0,7.7344,0.0000,0.0000,0.317965,22430,5.592784,41.778351,38.298969,9.716495,4.613402,11.310745,1666,543,6,2627,197,228,5729,88.403846,11.596154,3.189215
85610,85611,Breakdown,151.196,-33.9220,2018-08-15 04:50:00,15-08-2018 04:50,Wednesday,UNKNOWN,0.000000,Bus,Unknown,['RMS'],BREAKDOWN Bus,False,NaN,Exercise caution,Avoid the area,NaN,Lanes closed,Northbound,Botany Road,1,1,Alexandria,Unknown,117011635,Mascot,11701,Botany,117,Sydney - City and Inner South,3.0501,http://linked.data.gov.au/dataset/asgsed3/SA2/...,117011635,3.0501,7.158851,0.000000,15.885392,3.114614,3.556988,19.325149,0.000000,3.525824,52.566818,0.665311,274,25,1,188,58,3.043796,448,0.322284,0.001368,90,0.1779,0.0834,0.0000,0.7949,0.0,0.1966,0.0,1.6856,0.1117,0.0000,0.538610,21581,20.092988,50.389545,22.970596,4.687107,1.859764,9.123766,1314,1639,37,3013,309,903,4585,78.280807,21.719193,2.976042

In [38]:
df['Primary_Vehicle'].value_counts()

Primary_Vehicle
Car                  49806
Truck                14914
Unknown               9682
Multiple vehicles     6537
Bus                   3479
Motorcycle            1051
Others                 142
Name: count, dtype: int64

In [39]:
df['Secondary_Vehicle'].value_counts()

Secondary_Vehicle
Car                  18858
Unknown              10457
Multiple vehicles     6500
Motorcycle            1629
Pedestrian             962
Bicycle                380
Truck                  255
Bus                     63
Others                   6
Name: count, dtype: int64

In [40]:
df.columns

Index(['Incident ID', 'Main_Category', 'Longitude', 'Latitude', 'Start_Time',
       'Last_Updated', 'Day', 'End_Time', 'Duration_in_Minutes',
       'Primary_Vehicle', 'Secondary_Vehicle', 'Attending_Groups',
       'Display_Name', 'Is_Major_Incident', 'Diversions', 'Advice_A',
       'Advice_B', 'Other_Advice', 'Closure_Type', 'Direction', 'Main_Street',
       'Affected_Lanes', 'Actual_Number_of_Lanes ', 'Suburb', 'Traffic_Volume',
       'SA2_CODE21', 'SA2_NAME21', 'SA3_CODE21', 'SA3_NAME21', 'SA4_CODE21',
       'SA4_NAME21', 'AREASQKM21', 'LOCI_URI21', '0_ZID', '1_Area', '2_ML',
       '3_TRL', '4_PRL', '5_SRL', '6_TrRL', '7_RRL', '8_LsRL', '9_URL',
       '10_ToRL', '11_EoR', '12_NoN', '13_NDEs', '14_NNC2L', '15_NNC3L',
       '16_NNC4L', '17_AND', '18_NE', '19_MCI', '20_CoI', '21 NBS', '22_CA',
       '23_EA', '24_HA', '25_IA', '26_OA', '27_PA', '28_PrA', '29_RA', '30_TA',
       '31_WbA', '32_EoLU', '33_TP', '34_PD0MV', '35_PD1MV', '36_PD2MV',
       '37_PD3MV', '38_PD≥4MV', '39_PUE', '40_AMI', '41_NPTtWbyPT',
       '42_NPTtWbyTx', '43_NPTtWbyCD', '44_NPTtWbyCP', '45_NPTtWbyO',
       '46_NPWfH', '47_PWCJH', '48_PBCJH', '49_ANP_FH'],
      dtype='object')

In [41]:
df['Attending_Groups'].value_counts()[:20]

Attending_Groups
['Transport for NSW']                                       13101
['Emergency services', 'Transport for NSW']                 11347
unknown                                                     10927
['Emergency services']                                       8988
['RMS']                                                      7236
['Emergency service(s)', 'RMS']                              6252
['Emergency service(s)']                                     5257
['Motorway Crew']                                            4034
['Motorway crew']                                            1997
['Emergency services', 'Tow Truck']                          1332
['Tow Truck', 'Transport for NSW']                           1171
['Emergency services', 'Tow Truck', 'Transport for NSW']     1008
['Transport for NSW', 'Emergency services']                   963
['Mechanic']                                                  842
['Heavy vehicle tow truck', 'Transport for NSW']              744
['Emergency services', 'Motorway Crew']                       704
['Tow Truck']                                                 670
['Tow truck']                                                 632
['Mechanic', 'Transport for NSW']                             556
['Emergency service(s)', 'Tow truck']                         503
Name: count, dtype: int64

In [42]:
import pandas as pd

# Step 1: Convert string representation of lists into actual lists
# Replace empty string lists with a placeholder for easier handling
df['Attending_Groups'] = df['Attending_Groups'].replace('unknown', '[]')

df['Attending_Groups'] = df['Attending_Groups'].replace("[' ']", "['Other']").apply(eval)

# Step 2: Identify unique groups and aggregate less frequent ones if necessary
all_groups = set(group for sublist in df['Attending_Groups'] for group in sublist)

# Step 3: Create binary columns for each unique group
for group in all_groups:
    # Create a new column for each group, marking 1 if the group is present, 0 otherwise
    df[group] = df['Attending_Groups'].apply(lambda x: 1 if group in x else 0)

C:\Users\A\AppData\Local\Temp\ipykernel_33552\299310430.py:17: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[group] = df['Attending_Groups'].apply(lambda x: 1 if group in x else 0)
C:\Users\A\AppData\Local\Temp\ipykernel_33552\299310430.py:17: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[group] = df['Attending_Groups'].apply(lambda x: 1 if group in x else 0)
C:\Users\A\AppData\Local\Temp\ipykernel_33552\299310430.py:17: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[group] = df['Attending_Groups'].apply(lambda x: 1 if group in x else 0)
C:\Users\A\AppData\Local\Temp\ipykernel_33552\299310430.py:17: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[group] = df['Attending_Groups'].apply(lambda x: 1 if group in x else 0)
C:\Users\A\AppData\Local\Temp\ipykernel_33552\299310430.py:17: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[group] = df['Attending_Groups'].apply(lambda x: 1 if group in x else 0)
C:\Users\A\AppData\Local\Temp\ipykernel_33552\299310430.py:17: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[group] = df['Attending_Groups'].apply(lambda x: 1 if group in x else 0)
C:\Users\A\AppData\Local\Temp\ipykernel_33552\299310430.py:17: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[group] = df['Attending_Groups'].apply(lambda x: 1 if group in x else 0)
C:\Users\A\AppData\Local\Temp\ipykernel_33552\299310430.py:17: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[group] = df['Attending_Groups'].apply(lambda x: 1 if group in x else 0)
C:\Users\A\AppData\Local\Temp\ipykernel_33552\299310430.py:17: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[group] = df['Attending_Groups'].apply(lambda x: 1 if group in x else 0)
C:\Users\A\AppData\Local\Temp\ipykernel_33552\299310430.py:17: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[group] = df['Attending_Groups'].apply(lambda x: 1 if group in x else 0)

In [43]:
df

,Incident ID,Main_Category,Longitude,Latitude,Start_Time,Last_Updated,Day,End_Time,Duration_in_Minutes,Primary_Vehicle,Secondary_Vehicle,Attending_Groups,Display_Name,Is_Major_Incident,Diversions,Advice_A,Advice_B,Other_Advice,Closure_Type,Direction,Main_Street,Affected_Lanes,Actual_Number_of_Lanes,Suburb,Traffic_Volume,SA2_CODE21,SA2_NAME21,SA3_CODE21,SA3_NAME21,SA4_CODE21,SA4_NAME21,AREASQKM21,LOCI_URI21,0_ZID,1_Area,2_ML,3_TRL,4_PRL,5_SRL,6_TrRL,7_RRL,8_LsRL,9_URL,10_ToRL,11_EoR,12_NoN,13_NDEs,14_NNC2L,15_NNC3L,16_NNC4L,17_AND,18_NE,19_MCI,20_CoI,21 NBS,22_CA,23_EA,24_HA,25_IA,26_OA,27_PA,28_PrA,29_RA,30_TA,31_WbA,32_EoLU,33_TP,34_PD0MV,35_PD1MV,36_PD2MV,37_PD3MV,38_PD≥4MV,39_PUE,40_AMI,41_NPTtWbyPT,42_NPTtWbyTx,43_NPTtWbyCD,44_NPTtWbyCP,45_NPTtWbyO,46_NPWfH,47_PWCJH,48_PBCJH,49_ANP_FH,Bus mechanic,Traffic control,Tow Truck,Bus marshall,Transport Commander,Light Rail,STA tow truck,Ausgrid,Motorway Crew,Traffic controllers,HAZMAT,Downer Mouchel,Mechanioc,Sydney light rail,State transit,WestConnex,Rural Fire Service,Mehanic,Crime Scene Investigators Heavy Vehicle Inspectors,NMRA,Mechanic attending,mechanic,Mechanic,Signal Maintenance Crew,STA Mechanic,bus company,Maintenance,Heavy vehicle tow truck,NorthConnex,Bus company,Contractor,Nechanic,maintenance,Mehcanic,Crash Investigation Unit,Northconnex,Tow truck,Crime Investigation Unit,nrma,NBRMA,Signal crew,Hazmat,Road Engineers,crane,CSI,Sweeper,Emergency services,Local council,NRMA tow,mechanics,Crime,Sydney Ports,Heavy Vehicle Inspector,SES,Roadside Assistance,Light rail,tyrefitter,Crime Scene Unit,Sydney Buses,Helicopter,Crime Scene,STA Mechanic,Utility Company,Mechanics,CBD Light Rail,tyre fitter,EPA,bus mechanic,Heavy Vehicle Inspectors,NorthConnex Mechanic,Heavy vehicle inspector,Signal technician,Transport for NSW,NRMA,STA mechanic,LTJV,Tyre fitter,Utility company,Tyre Fitter,Maintenance Crew,maintenance crew,Crane,Signal Technician,Motorway crew,STA mechanic,Bobcat,Other,Emergency service(s),Westconnex,Forklift,Crime Scene Investigation,Heavy tow truck,Local Council,sta,RMS,State Transit Authority,Heavy vehicle inspector,Transdev mechanic,STA,Crime scene investigation
0,1,Crash,151.058,-33.9431,2018-08-14 19:21:00,14-08-2018 20:00,Tuesday,14-08-2018 20:00,39.319950,Car,Car,[Emergency services],accident 2 cars,False,unknown,Exercise caution,Allow extra travel time,unknown,Affected,Eastbound,M5 Motorway,99,99,Riverwood,Unknown,119021366,Punchbowl,11902,Canterbury,119,Sydney - Inner South West,5.2458,http://linked.data.gov.au/dataset/asgsed3/SA2/...,119021366,5.2458,7.488104,3.038780,2.236683,6.602571,2.551265,42.103090,0.000000,0.115587,64.136080,0.504771,325,40,7,260,17,2.790769,491,0.258915,0.001351,210,0.0938,0.1211,0.0000,0.7056,0.0,0.5171,0.0,3.8082,0.0000,0.0000,0.386385,21537,11.297837,37.886855,30.565724,12.296173,7.953411,12.109393,831,342,16,2806,276,260,1520,67.634460,32.365540,3.713468,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,2,Breakdown,151.159,-33.8096,2018-08-15 00:47:00,15-08-2018 00:59,Wednesday,15-08-2018 00:59,12.029000,Car,NaN,[Motorway Crew],breakdown car,False,unknown,Exercise caution,NaN,unknown,Lanes closed,Westbound,Lane Cove Tunnel,1,2,Lane Cove North,Unknown,121011399,Chatswood (West) - Lane Cove North,12101,Chatswood - Lane Cove,121,Sydney - North Sydney and Hornsby,5.5372,http://linked.data.gov.au/dataset/asgsed3/SA2/...,121011399,5.5372,8.365015,2.097842,7.903368,4.617769,0.232704,40.351141,0.000000,0.739679,64.307518,0.515889,269,59,6,176,28,2.643123,383,0.215760,0.001839,210,0.0080,0.1223,0.0238,0.0000,0.0,1.3725,0.0,4.0106,0.0000,0.0000,0.302463,21270,10.253288,52.715538,29.067219,5.723332,2.240623,7.776211,1643,651,6,2652,227,514,6070,88.007396,11.992604,3.023239,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,3,Crash,150.875,-33.7344,2018-08-15 01:12:00,15-08-2018 01:29,Wednesday,15-08-2018 01:29,16.956667,Car,NaN,"[Emergency services, Motorway Crew]",accident car,False,unknown,NaN,NaN,unknown,Lanes closed,Westbound,Westlink M7 off-ramp,1,1,Quakers Hill,Unknown,116011304,Blacktown (North) - Marayong,11601,Blacktown,116,Sydney - Blacktown,7.3828,http://linked.data.gov.au/dataset/asgsed3/SA2/...,116011304,7.3828,9.051683,0.000000,12.307502,5.297219,9.525819,56.104489,0.000000,0.128916,92.415628,0.523895,468,112,2,307,47,2.617521,631,0.176155,0.001177,234,0.0000,0.2768,0.0000,0.3180,0.0,0.9027,0.0,5.6929,0.1924,0.0000,0.352217,20570,8.724832,41.000610,34.716290,10.600976,4.957291,9.688867,1030,532,18,3686,323,256,2398,67.554766,32.445234,3.341706,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,4,Crash,150.973,-33.8172,2018-08-15 01:27:00,15-08-2018 02:09,Wednesday,15-08-2018 02:09,42.804117,Truck,Car,"[Emergency services, Transport for NSW]",accident car,False,unknown,Exercise caution,Allow extra travel time,unknown,Affected,Westbound,M4 Motorway,1,1,South Wentworthville,Moderate,125041589,Wentworthville - Westmead,12504,Parramatta,125,Sydney - Parramatta,3.9355,http://linked.data.gov.au/dataset/asgsed3/SA2/...,125041589,3.9355,9.698544,8.941532,0.016410,1.416884,5.140331,32.486126,0.000000,0.512046,58.211873,0.547443,266,39,7,188,31,2.804511,402,0.259962,0.001650,174,0.1010,0.1006,0.0236,0.0000,0.0,0.2426,0.0,3.1727,0.2950,0.0000,0.329226,21564,13.219616,56.830135,22.857143,4.804549,2.288557,9.956409,1302,902,11,2707,291,311,4379,78.956666,21.043334,3.248887,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,5,Crash,150.981,-33.7919,2018-08-15 01:37:00,15-08-2018 02:18,Wednesday,15-08-2018 02:18,40.840000,Multiple vehicles,Multiple vehicles,[Tow Truck],accident 3 vehicles,False,unknown,Exercise caution,NaN,unknown,Affected,Southbound,Old Windsor Road,99,99,Northmead,Unknown,125041493,Toongabbie - Constitution Hill,12504,Parramatta,125,Sydney - Parramatta,7.4795,http://linked.data.gov.au/dataset/asgsed3/SA2/...,125041493,7.4795,0.000000,9.092391,0.000000,7.092430,13.338771,51.982067,0.000000,4.266734,85.772393,0.515169,454,105,3,322,23,2.585903,598,0.160576,0.001272,194,0.4036,0.1788,0.0000,0.0000,0.0,0.8217,0.0,6.0754,0.0000,0.0000,0.285901,22840,8.134605,39.745628,35.466349,10.996290,5.657128,9.071804,1170,589,18,3487,314,261,3798,77.384802,22.615198,3.295874,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85606,85607,Breakdown,151.193,-33.8877,2018-08-14 08:09:00,14-08-2018 08:09,Tuesday,UNKNOWN,0.073550,Car,Unknown,"[RMS, Tow truck]",BREAKDOWN Car,False,NaN,NaN,NaN,NaN,Lanes closed,Westbound,Cleveland Street,99,99,Camperdown,Unknown,117031638,Camperdown - Darlington,11703,Sydney Inner City,117,Sydney - City and Inner South,1.7106,http://linked.data.gov.au/dataset/asgsed3/SA2/...,117031638,1.7106,0.000000,6.229383,0.770780,1.555551,2.349888,12.909696,0.974891,0.628599,25.418788,0.609042,156,17,5,105,29,2.935897,275,0.390879,0.002070,44,0.1061,0.7496,0.0680,0.0285,0.0,0.1834,0.0,0.5750,0.0000,0.0000,0.580342,8323,25.450139,53.116343,17.659280,2.770083,1.004155,8.626697,1457,347,10,726,68,587,2683,89.198132,10.801868,2.643437,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
85607,85608,Crash,151.054,-33.7991,2018-08-15 04:44:00,15-08-2018 04:44,Wednesday,UNKNOWN,0.000000,Unknown,Unknown,"[RMS, Tow truck]",ACCIDENT 2 cars,False,NaN,NaN,NaN,NaN,Lanes closed,Eastbound,Kissing Point Road,1,2,Dundas,Unknown,125021477,Ermington - Rydalmere,12502,Carlingford,125,Sydney - Parramatta,9.8655,http://linked.data.gov.au/dataset/asgsed3/SA2/...,125021477,9.8655,0.000000,21.451793,9.077881,1.305794,13.243906,62.631529,0.000000,5.247824,112.958727,0.560480,607,100,5,408,92,2.823723,881,0.227461,0.000783,293,1.8816,0.5680,0.0609,0.1085,0.0,1.3128,0.0,5.6133,0.0000,0.3204,0.548046,24612,8.555502,37.190984,37.869607,10.954920,5.428987,9.198765,1177,347,12,4061,298,276,4287,80.158441,19.841559,3.276092,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
85608,85609,Crash,151.066,-33.7527,2018-08-15 04:45:00,15-08-2018 04:45,Wednesday,UNKNOWN,0.000000,Multiple vehicles,Unknown,[],ACCIDENT 3 vehicles,False,NaN,Allow extra travel time,NaN,NaN,Affected,Southbound,Beecroft Road,99,99,Beecroft,Heavy,126011496,Pennant Hills - Cheltenham,12601,Pennant Hills - Epping,126,Sydney - Ryde,13.2936,http://linked.data.gov.au/dataset/asgsed3/SA2/...,126011496,13.2936,32.246711,8.952339,7.362372,2.310562,5.986376,67.291924,0.000000,1.074018,125.224302,0.563783,460,115,5,296,41,2.597826,627,0.183607,0.001172,216,0.2145,0.3761,0.0000,0.0000,0.0,4.6254,0.0,8.0776,0.0000,0.0000,0.363720,21731,4.697707,35.830438,41.987491,11.994441,5.489924,8.872118,1557,422,0,2902,224,282,5386,88.021691,11.978309,3.281978,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
85609,85610,Breakdown,151.154,-33.7587,2018-08-15 04:47:00,15-08-2018 04:47,Wednesday,UNKNOWN,0.000000,Truck,Unknown,[RMS],BREAKDOWN Truck,False,NaN,Allow extra travel time,NaN,NaN,Lanes closed,Southbound,Pacific Highway,1,2,Gordon,Moderate,121031407,Gordon - Killara,12103,Ku-ring-gai,121,Sydney - North Sydney and Hornsby,11.6713,http://linked.data.gov.au/dataset/asgsed3/SA2/...,121031407,11.6713,0.000000,8.402822,0.000000,3.362577,9.581556,72.142489,0.000000,0.000000,93.489444,0.334247,412,81,0,289,41,2.711165,577,0.202686,0.001240,220,0.1110,0.1334,0.0000,0.0000,0.0,3.6925,0.0,7.7344,0.0000,0.0000,0.317965,22430,5.592784,41.778351,38.298969,9.716495,4.613402,11.310745,1666,543,6,2627,197,228,5729,88.403846,11.596154,3.189215,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
85610,85611,Breakdown,151.196,-33.9220,2018-08-15 04:50:00,15-08-2018 04:50,Wednesday,UNKNOWN,0.000000,Bus,Unknown,[RMS],BREAKDOWN Bus,False,NaN,Exercise caution,Avoid the area,NaN,Lanes closed,Northbound,Botany Road,1,1,Alexandria,Unknown,117011635,Mascot,11701,Botany,117,Sydney - City and Inner South,3.0501,http://linked.data.gov.au/dataset/asgsed3/SA2/...,117011635,3.0501,7.158851,0.000000,15.885392,3.114614,3.556988,19.325149,0.000000,3.525824,52.566818,0.665311,274,25,1,188,58,3.043796,448,0.322284,0.001368,90,0.1779,0.0834,0.0000,0.7949,0.0,0.1966,0.0,1.6856,0.1117,0.0000,0.538610,21581,20.092988,50.389545,22.970596,4.687107,1.859764,9.123766,1314,1639,37,3013,309,903,4585,78.280807,21.719193,2.976042,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0

In [44]:
df = df.drop(['0_ZID', 'LOCI_URI21','SA2_NAME21','Other_Advice','Diversions','Attending_Groups','End_Time','Last_Updated','Incident ID'],axis=1)

In [45]:
from sklearn.preprocessing import LabelEncoder
import re

def extract_info_from_display_name(row):
    incident_type = 'unknown'
    num_vehicles_involved = 1  # Default to 1 if specific number is not mentioned

    if 'breakdown' in row.lower():
        incident_type = 'breakdown'
    elif 'crash' in row.lower():
        incident_type = 'crash'
    elif 'accident' in row.lower():
        incident_type = 'accident'

    # Extract number of cars/vehicles if specified
    numbers = re.findall(r'(\d+)\s*(cars|vehicles)', row, re.IGNORECASE)
    if numbers:
        # If numbers are found, take the first one as the count (assuming one type of vehicle is mentioned)
        num_vehicles_involved = int(numbers[0][0])
    elif 'car' in row.lower() or 'vehicle' in row.lower():
        # Assume at least one vehicle is involved if specific numbers aren't mentioned
        num_vehicles_involved = 1

    return pd.Series([incident_type, num_vehicles_involved])

# Apply the function to the DataFrame
df[['Incident_Type', 'Num_Vehicles_Involved']] = df['Display_Name'].apply(extract_info_from_display_name)


# label_encoders = {}
# for column in ['Main_Category', 'Day', 'Incident_Type','Primary_Vehicle', 'Secondary_Vehicle', 'Is_Major_Incident', 'Closure_Type', 'Direction', 'Traffic_Volume','Advice_A','Advice_B','SA3_NAME21','SA4_NAME21','Suburb','Main_Street']:
#     if column in df.columns:
#         le = LabelEncoder()
#         df[column] = le.fit_transform(df[column].astype(str))
#         label_encoders[column] = le

# Extracting information from "Display_Name"

C:\Users\A\AppData\Local\Temp\ipykernel_33552\529302796.py:27: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[['Incident_Type', 'Num_Vehicles_Involved']] = df['Display_Name'].apply(extract_info_from_display_name)
C:\Users\A\AppData\Local\Temp\ipykernel_33552\529302796.py:27: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[['Incident_Type', 'Num_Vehicles_Involved']] = df['Display_Name'].apply(extract_info_from_display_name)

In [46]:
import pandas as pd
from datetime import datetime

def extract_month_and_hour(start_time):
    # Check if the input is a string and parse it if necessary
    if isinstance(start_time, str):
        dt = datetime.strptime(start_time, '%d-%m-%Y %H:%M')
    else:
        dt = start_time
    # Extract month and hour
    month = dt.month
    hour = dt.hour
    return pd.Series([month, hour])

# Sample DataFrame for demonstration
# data = {'Start_Time': ['01-01-2023 08:00', '02-02-2023 09:30', '03-03-2023 10:45']}
# df = pd.DataFrame(data)
df['Start_Time'] = pd.to_datetime(df['Start_Time'], format='%d-%m-%Y %H:%M')

# Apply the function to the DataFrame and create new columns for month and hour
df[['Month', 'Hour']] = df['Start_Time'].apply(extract_month_and_hour)

# Drop unnecessary columns
df = df.drop(['Start_Time'], axis=1)

# Display the DataFrame
df

C:\Users\A\AppData\Local\Temp\ipykernel_33552\2402169871.py:21: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[['Month', 'Hour']] = df['Start_Time'].apply(extract_month_and_hour)
C:\Users\A\AppData\Local\Temp\ipykernel_33552\2402169871.py:21: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[['Month', 'Hour']] = df['Start_Time'].apply(extract_month_and_hour)

,Main_Category,Longitude,Latitude,Day,Duration_in_Minutes,Primary_Vehicle,Secondary_Vehicle,Display_Name,Is_Major_Incident,Advice_A,Advice_B,Closure_Type,Direction,Main_Street,Affected_Lanes,Actual_Number_of_Lanes,Suburb,Traffic_Volume,SA2_CODE21,SA3_CODE21,SA3_NAME21,SA4_CODE21,SA4_NAME21,AREASQKM21,1_Area,2_ML,3_TRL,4_PRL,5_SRL,6_TrRL,7_RRL,8_LsRL,9_URL,10_ToRL,11_EoR,12_NoN,13_NDEs,14_NNC2L,15_NNC3L,16_NNC4L,17_AND,18_NE,19_MCI,20_CoI,21 NBS,22_CA,23_EA,24_HA,25_IA,26_OA,27_PA,28_PrA,29_RA,30_TA,31_WbA,32_EoLU,33_TP,34_PD0MV,35_PD1MV,36_PD2MV,37_PD3MV,38_PD≥4MV,39_PUE,40_AMI,41_NPTtWbyPT,42_NPTtWbyTx,43_NPTtWbyCD,44_NPTtWbyCP,45_NPTtWbyO,46_NPWfH,47_PWCJH,48_PBCJH,49_ANP_FH,Bus mechanic,Traffic control,Tow Truck,Bus marshall,Transport Commander,Light Rail,STA tow truck,Ausgrid,Motorway Crew,Traffic controllers,HAZMAT,Downer Mouchel,Mechanioc,Sydney light rail,State transit,WestConnex,Rural Fire Service,Mehanic,Crime Scene Investigators Heavy Vehicle Inspectors,NMRA,Mechanic attending,mechanic,Mechanic,Signal Maintenance Crew,STA Mechanic,bus company,Maintenance,Heavy vehicle tow truck,NorthConnex,Bus company,Contractor,Nechanic,maintenance,Mehcanic,Crash Investigation Unit,Northconnex,Tow truck,Crime Investigation Unit,nrma,NBRMA,Signal crew,Hazmat,Road Engineers,crane,CSI,Sweeper,Emergency services,Local council,NRMA tow,mechanics,Crime,Sydney Ports,Heavy Vehicle Inspector,SES,Roadside Assistance,Light rail,tyrefitter,Crime Scene Unit,Sydney Buses,Helicopter,Crime Scene,STA Mechanic,Utility Company,Mechanics,CBD Light Rail,tyre fitter,EPA,bus mechanic,Heavy Vehicle Inspectors,NorthConnex Mechanic,Heavy vehicle inspector,Signal technician,Transport for NSW,NRMA,STA mechanic,LTJV,Tyre fitter,Utility company,Tyre Fitter,Maintenance Crew,maintenance crew,Crane,Signal Technician,Motorway crew,STA mechanic,Bobcat,Other,Emergency service(s),Westconnex,Forklift,Crime Scene Investigation,Heavy tow truck,Local Council,sta,RMS,State Transit Authority,Heavy vehicle inspector,Transdev mechanic,STA,Crime scene investigation,Incident_Type,Num_Vehicles_Involved,Month,Hour
0,Crash,151.058,-33.9431,Tuesday,39.319950,Car,Car,accident 2 cars,False,Exercise caution,Allow extra travel time,Affected,Eastbound,M5 Motorway,99,99,Riverwood,Unknown,119021366,11902,Canterbury,119,Sydney - Inner South West,5.2458,5.2458,7.488104,3.038780,2.236683,6.602571,2.551265,42.103090,0.000000,0.115587,64.136080,0.504771,325,40,7,260,17,2.790769,491,0.258915,0.001351,210,0.0938,0.1211,0.0000,0.7056,0.0,0.5171,0.0,3.8082,0.0000,0.0000,0.386385,21537,11.297837,37.886855,30.565724,12.296173,7.953411,12.109393,831,342,16,2806,276,260,1520,67.634460,32.365540,3.713468,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,accident,2,8,19
1,Breakdown,151.159,-33.8096,Wednesday,12.029000,Car,NaN,breakdown car,False,Exercise caution,NaN,Lanes closed,Westbound,Lane Cove Tunnel,1,2,Lane Cove North,Unknown,121011399,12101,Chatswood - Lane Cove,121,Sydney - North Sydney and Hornsby,5.5372,5.5372,8.365015,2.097842,7.903368,4.617769,0.232704,40.351141,0.000000,0.739679,64.307518,0.515889,269,59,6,176,28,2.643123,383,0.215760,0.001839,210,0.0080,0.1223,0.0238,0.0000,0.0,1.3725,0.0,4.0106,0.0000,0.0000,0.302463,21270,10.253288,52.715538,29.067219,5.723332,2.240623,7.776211,1643,651,6,2652,227,514,6070,88.007396,11.992604,3.023239,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,breakdown,1,8,0
2,Crash,150.875,-33.7344,Wednesday,16.956667,Car,NaN,accident car,False,NaN,NaN,Lanes closed,Westbound,Westlink M7 off-ramp,1,1,Quakers Hill,Unknown,116011304,11601,Blacktown,116,Sydney - Blacktown,7.3828,7.3828,9.051683,0.000000,12.307502,5.297219,9.525819,56.104489,0.000000,0.128916,92.415628,0.523895,468,112,2,307,47,2.617521,631,0.176155,0.001177,234,0.0000,0.2768,0.0000,0.3180,0.0,0.9027,0.0,5.6929,0.1924,0.0000,0.352217,20570,8.724832,41.000610,34.716290,10.600976,4.957291,9.688867,1030,532,18,3686,323,256,2398,67.554766,32.445234,3.341706,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,accident,1,8,1
3,Crash,150.973,-33.8172,Wednesday,42.804117,Truck,Car,accident car,False,Exercise caution,Allow extra travel time,Affected,Westbound,M4 Motorway,1,1,South Wentworthville,Moderate,125041589,12504,Parramatta,125,Sydney - Parramatta,3.9355,3.9355,9.698544,8.941532,0.016410,1.416884,5.140331,32.486126,0.000000,0.512046,58.211873,0.547443,266,39,7,188,31,2.804511,402,0.259962,0.001650,174,0.1010,0.1006,0.0236,0.0000,0.0,0.2426,0.0,3.1727,0.2950,0.0000,0.329226,21564,13.219616,56.830135,22.857143,4.804549,2.288557,9.956409,1302,902,11,2707,291,311,4379,78.956666,21.043334,3.248887,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,accident,1,8,1
4,Crash,150.981,-33.7919,Wednesday,40.840000,Multiple vehicles,Multiple vehicles,accident 3 vehicles,False,Exercise caution,NaN,Affected,Southbound,Old Windsor Road,99,99,Northmead,Unknown,125041493,12504,Parramatta,125,Sydney - Parramatta,7.4795,7.4795,0.000000,9.092391,0.000000,7.092430,13.338771,51.982067,0.000000,4.266734,85.772393,0.515169,454,105,3,322,23,2.585903,598,0.160576,0.001272,194,0.4036,0.1788,0.0000,0.0000,0.0,0.8217,0.0,6.0754,0.0000,0.0000,0.285901,22840,8.134605,39.745628,35.466349,10.996290,5.657128,9.071804,1170,589,18,3487,314,261,3798,77.384802,22.615198,3.295874,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,accident,3,8,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85606,Breakdown,151.193,-33.8877,Tuesday,0.073550,Car,Unknown,BREAKDOWN Car,False,NaN,NaN,Lanes closed,Westbound,Cleveland Street,99,99,Camperdown,Unknown,117031638,11703,Sydney Inner City,117,Sydney - City and Inner South,1.7106,1.7106,0.000000,6.229383,0.770780,1.555551,2.349888,12.909696,0.974891,0.628599,25.418788,0.609042,156,17,5,105,29,2.935897,275,0.390879,0.002070,44,0.1061,0.7496,0.0680,0.0285,0.0,0.1834,0.0,0.5750,0.0000,0.0000,0.580342,8323,25.450139,53.116343,17.659280,2.770083,1.004155,8.626697,1457,347,10,726,68,587,2683,89.198132,10.801868,2.643437,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,breakdown,1,8,8
85607,Crash,151.054,-33.7991,Wednesday,0.000000,Unknown,Unknown,ACCIDENT 2 cars,False,NaN,NaN,Lanes closed,Eastbound,Kissing Point Road,1,2,Dundas,Unknown,125021477,12502,Carlingford,125,Sydney - Parramatta,9.8655,9.8655,0.000000,21.451793,9.077881,1.305794,13.243906,62.631529,0.000000,5.247824,112.958727,0.560480,607,100,5,408,92,2.823723,881,0.227461,0.000783,293,1.8816,0.5680,0.0609,0.1085,0.0,1.3128,0.0,5.6133,0.0000,0.3204,0.548046,24612,8.555502,37.190984,37.869607,10.954920,5.428987,9.198765,1177,347,12,4061,298,276,4287,80.158441,19.841559,3.276092,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,accident,2,8,4
85608,Crash,151.066,-33.7527,Wednesday,0.000000,Multiple vehicles,Unknown,ACCIDENT 3 vehicles,False,Allow extra travel time,NaN,Affected,Southbound,Beecroft Road,99,99,Beecroft,Heavy,126011496,12601,Pennant Hills - Epping,126,Sydney - Ryde,13.2936,13.2936,32.246711,8.952339,7.362372,2.310562,5.986376,67.291924,0.000000,1.074018,125.224302,0.563783,460,115,5,296,41,2.597826,627,0.183607,0.001172,216,0.2145,0.3761,0.0000,0.0000,0.0,4.6254,0.0,8.0776,0.0000,0.0000,0.363720,21731,4.697707,35.830438,41.987491,11.994441,5.489924,8.872118,1557,422,0,2902,224,282,5386,88.021691,11.978309,3.281978,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,accident,3,8,4
85609,Breakdown,151.154,-33.7587,Wednesday,0.000000,Truck,Unknown,BREAKDOWN Truck,False,Allow extra travel time,NaN,Lanes closed,Southbound,Pacific Highway,1,2,Gordon,Moderate,121031407,12103,Ku-ring-gai,121,Sydney - North Sydney and Hornsby,11.6713,11.6713,0.000000,8.402822,0.000000,3.362577,9.581556,72.142489,0.000000,0.000000,93.489444,0.334247,412,81,0,289,41,2.711165,577,0.202686,0.001240,220,0.1110,0.1334,0.0000,0.0000,0.0,3.6925,0.0,7.7344,0.0000,0.0000,0.317965,22430,5.592784,41.778351,38.298969,9.716495,4.613402,11.310745,1666,543,6,2627,197,228,5729,88.403846,11.596154,3.189215,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,breakdown,1,8,4
85610,Breakdown,151.196,-33.9220,Wednesday,0.000000,Bus,Unknown,BREAKDOWN Bus,False,Exercise caution,Avoid the area,Lanes closed,Northbound,Botany Road,1,1,Alexandria,Unknown,117011635,11701,Botany,117,Sydney - City and Inner South,3.0501,3.0501,7.158851,0.000000,15.885392,3.114614,3.556988,19.325149,0.000000,3.525824,52.566818,0.665311,274,25,1,188,58,3.043796,448,0.322284,0.001368,90,0.1779,0.0834,0.0000,0.7949,0.0,0.1966,0.0,1.6856,0.1117,0.0000,0.538610,21581,20.092988,50.389545,22.970596,4.687107,1.859764,9.123766,1314,1639,37,3013,309,903,4585,78.280807,21.719193,2.976042,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,breakdown,1,8,4

In [47]:
# from datetime import datetime
# def extract_month_and_hour(start_time_str):
#     # Parse the start time string to a datetime object
#     dt = datetime.strptime(start_time_str, '%d-%m-%Y %H:%M')
#     # Extract month and hour
#     month = dt.month
#     hour = dt.hour
#     return pd.Series([month, hour])

# # Apply the function to the DataFrame and create new columns for month and hour
# df[['Month', 'Hour']] = df['Start_Time'].apply(extract_month_and_hour)

KeyError: 'Start_Time'

In [49]:
df = df.drop(['Display_Name'],axis=1)#,'Start_Time'

In [50]:
df.dtypes.T

Main_Category                 object
Longitude                    float64
Latitude                     float64
Day                           object
Duration_in_Minutes          float64
                              ...
Crime scene investigation      int64
Incident_Type                 object
Num_Vehicles_Involved          int64
Month                          int64
Hour                           int64
Length: 176, dtype: object

In [51]:
import ast
# def count_attending(attending_list):
#     # Handle empty or non-list cases
#     if pd.isna(attending_list) or attending_list == ' ':
#         return 0
#     else:
#         return len(ast.literal_eval(attending_list))
    
# df['count_attending'] = df['Attending_Groups'].apply(lambda x: count_attending(x))

reference_point = (-33.87324469333478, 151.20665137317067)

from geopy.distance import geodesic
df['distance_to_CBD'] = df.apply(lambda row: geodesic((row['Latitude'], row['Longitude']), reference_point).km, axis=1)

# def is_multi_vehicle(subcategory):
#     multi_vehicles = ['Car', 'Truck', np.nan, 'Bus', 'Car, In clearway', 'Van', 'Van, In clearway', 'Vehicle on fire', 'Trailer, In clearway', 'Bicycle']
#     return 0 if subcategory in multi_vehicles else 1

# Apply the function to create a new column 'multi_vehicle'
# df['multi_vehicle'] = df['subCategoryA'].apply(lambda x: is_multi_vehicle(x))

C:\Users\A\AppData\Local\Temp\ipykernel_33552\3537677232.py:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['distance_to_CBD'] = df.apply(lambda row: geodesic((row['Latitude'], row['Longitude']), reference_point).km, axis=1)

In [53]:
threshold = 0.98  # 90% threshold for imbalance
imbalanced_columns = []

for column in df.columns:
    if df[column].dtype == 'int64' or df[column].dtype == 'object':  # Checking for numerical and categorical data
        total_count = df[column].count()
        most_common_value_count = df[column].value_counts().iloc[0]
        if (most_common_value_count / total_count) > threshold:
            imbalanced_columns.append(column)
#             print(df[column].value_counts())

print("Highly imbalanced columns:", imbalanced_columns)

Highly imbalanced columns: ['Bus mechanic', 'Traffic control', 'Bus marshall', 'Transport Commander', 'Light Rail', 'STA tow truck', 'Ausgrid', 'Traffic controllers', 'HAZMAT', 'Downer Mouchel', 'Mechanioc', 'Sydney light rail', 'State transit', 'WestConnex', 'Rural Fire Service', 'Mehanic', 'Crime Scene Investigators Heavy Vehicle Inspectors', 'NMRA', 'Mechanic attending', 'mechanic', 'Signal Maintenance Crew', 'STA Mechanic', 'bus company', 'Maintenance', 'NorthConnex', 'Bus company', 'Contractor', 'Nechanic', 'maintenance', 'Mehcanic', 'Crash Investigation Unit', 'Northconnex', 'Crime Investigation Unit', 'nrma', 'NBRMA', 'Signal crew', 'Hazmat', 'Road Engineers', 'crane', 'CSI', 'Sweeper', 'Local council', 'NRMA tow', 'mechanics', 'Crime', 'Sydney Ports', 'Heavy Vehicle Inspector', 'SES', 'Roadside Assistance', 'Light rail', 'tyrefitter', 'Crime Scene Unit', 'Sydney Buses', 'Helicopter', 'Crime Scene', 'STA  Mechanic', 'Utility Company', 'Mechanics', 'CBD Light Rail', 'tyre fitter', 'EPA', 'bus mechanic', 'Heavy Vehicle Inspectors', 'NorthConnex Mechanic', 'Heavy vehicle  inspector', 'Signal technician', 'NRMA', 'STA  mechanic', 'LTJV', 'Tyre fitter', 'Utility company', 'Tyre Fitter', 'Maintenance Crew', 'maintenance crew', 'Crane', 'Signal Technician', 'STA mechanic', 'Bobcat', 'Other', 'Westconnex', 'Forklift', 'Crime Scene Investigation', 'Heavy tow truck', 'Local Council', 'sta', 'State Transit Authority', 'Heavy vehicle inspector', 'Transdev mechanic', 'STA', 'Crime scene investigation']

In [54]:
df = df.drop(columns=imbalanced_columns)

In [55]:
df.rename(columns={'Duration_in_Minutes': 'duration'}, inplace=True)

In [56]:
def sanitize_column_names(df):
    sanitized_names = []
    for col in df.columns:
        # Replace or remove special characters as needed, this is a simple replacement example
        sanitized = col.replace('{', '').replace('}', '').replace('[', '').replace(']', '').replace('"', '').replace(':', '')
        sanitized_names.append(sanitized)
    return sanitized_names

# Sanitize column names
sanitized_column_names = sanitize_column_names(df)

# Apply sanitized column names to the DataFrame
df.columns = sanitized_column_names

In [57]:
def analyze_data(df):
    """
    Print column names, top 2 most frequent values from each column, and type of each column.

    Parameters:
    df (pandas.DataFrame): The data frame to analyze.
    """
    for column in df.columns:
        print(f"Column: {column}")
        print(f"Type: {df[column].dtype}")
        print("Top 20 most frequent values:")
        print(df[column].value_counts().head(20))
        print("\n")

analyze_data(df)

Column: Main_Category
Type: object
Top 20 most frequent values:
Main_Category
Breakdown    46085
Crash        39165
Other          361
Name: count, dtype: int64


Column: Longitude
Type: float64
Top 20 most frequent values:
Longitude
151.211    1000
151.213     977
151.214     912
151.218     782
151.212     731
151.193     710
151.217     690
151.210     598
151.215     536
151.064     506
151.065     441
151.192     431
151.067     427
151.209     416
151.205     394
151.084     393
151.048     389
151.153     386
151.206     385
151.020     384
Name: count, dtype: int64


Column: Latitude
Type: float64
Top 20 most frequent values:
Latitude
-33.9362    316
-33.8435    212
-33.8310    211
-33.8679    208
-33.8270    197
-33.9361    187
-33.9295    185
-33.9459    166
-33.8749    161
-33.9363    156
-33.8569    147
-33.8276    143
-33.8753    142
-33.7586    142
-33.8268    134
-33.9446    126
-33.9461    122
-33.8747    121
-33.7395    120
-33.9009    117
Name: count, dtype: int64


Column: Day
Type: object
Top 20 most frequent values:
Day
Friday       14482
Thursday     14395
Wednesday    14051
Tuesday      13573
Monday       12771
Saturday      9401
Sunday        6938
Name: count, dtype: int64


Column: duration
Type: float64
Top 20 most frequent values:
duration
0.000000     92
0.000500     68
0.000783     50
0.000550     32
0.000767     31
0.000833     12
0.000567     11
23.364333     4
21.822833     3
25.677783     3
3.564000      3
17.709167     3
4.985667      3
11.188050     3
54.947667     3
22.683717     3
29.195400     3
33.112950     3
45.652667     3
4.779333      3
Name: count, dtype: int64


Column: Primary_Vehicle
Type: object
Top 20 most frequent values:
Primary_Vehicle
Car                  49806
Truck                14914
Unknown               9682
Multiple vehicles     6537
Bus                   3479
Motorcycle            1051
Others                 142
Name: count, dtype: int64


Column: Secondary_Vehicle
Type: object
Top 20 most frequent values:
Secondary_Vehicle
Car                  18858
Unknown              10457
Multiple vehicles     6500
Motorcycle            1629
Pedestrian             962
Bicycle                380
Truck                  255
Bus                     63
Others                   6
Name: count, dtype: int64


Column: Is_Major_Incident
Type: bool
Top 20 most frequent values:
Is_Major_Incident
False    84140
True      1471
Name: count, dtype: int64


Column: Advice_A
Type: object
Top 20 most frequent values:
Advice_A
Exercise caution                  41382
Reduce your speed                 15254
Allow extra travel time            9939
Reduce speed                       6992
Expect delays                      6703
Reduced speed limit                 873
Use an alternative route            354
Use diversions                      288
Avoid the area                      281
Use alternative route                75
Police are directing traffic         73
Check signage                        56
Police directing traffic             27
Plan your journey                     8
Keep right                            6
Delay journey                         4
Keep left                             3
Delay your journey                    3
Merge left                            2
Don't drive through floodwater        2
Name: count, dtype: int64


Column: Advice_B
Type: object
Top 20 most frequent values:
Advice_B
Exercise caution                              31429
Allow extra travel time                       12141
Reduce your speed                              6323
Expect delays                                  4759
Reduce speed                                   1192
Use an alternative route                        159
Use alternative route                           147
Exercise caution, Allow extra travel time       137
Allow extra travel time, Exercise caution       115
Reduced speed limit                              94
Exercise caution; Allow extra travel time        81
Exercise caution, Expect delays                  80
Use diversions                                   75
Exercise caution, Reduce your speed              71
Reduce your speed, Exercise caution              54
Reduce your speed, Expect delays                 41
Check signage, Exercise caution                  41
Avoid the area                                   38
Expect delays, Exercise caution                  34
Reduce your speed, Allow extra travel time       33
Name: count, dtype: int64


Column: Closure_Type
Type: object
Top 20 most frequent values:
Closure_Type
Lanes closed    52691
Affected        30979
Closed           1630
unknown           306
Name: count, dtype: int64


Column: Direction
Type: object
Top 20 most frequent values:
Direction
Southbound         21744
Northbound         21374
Westbound          17683
Eastbound          16290
Both directions     4957
All directions      1708
City bound          1648
Outbound             177
Inbound               12
Name: count, dtype: int64


Column: Main_Street
Type: object
Top 20 most frequent values:
Main_Street
M4 Motorway              4740
Pennant Hills Road       2510
Parramatta Road          2191
Great Western Highway    2051
Hume Highway             1881
Princes Highway          1868
M5 East Motorway         1805
Victoria Road            1745
Pacific Highway          1700
Warringah Freeway        1687
M5 Motorway              1663
Eastern Distributor      1463
M1 Pacific Motorway      1356
King Georges Road        1241
Southern Cross Drive     1215
General Holmes Drive     1155
Cumberland Highway       1111
Western Distributor      1087
Centenary Drive           944
M7 Motorway               904
Name: count, dtype: int64


Column: Affected_Lanes
Type: int64
Top 20 most frequent values:
Affected_Lanes
1     50077
99    32414
2      3120
Name: count, dtype: int64


Column: Actual_Number_of_Lanes
Type: int64
Top 20 most frequent values:
Actual_Number_of_Lanes
99    36348
2     25274
1     13918
3      7362
4      2709
Name: count, dtype: int64


Column: Suburb
Type: object
Top 20 most frequent values:
Suburb
Sydney           2292
Mascot           2069
North Sydney     1861
Arncliffe        1318
Eastern Creek    1299
Cowan            1270
Moore Park       1007
Granville         995
Strathfield       957
Rozelle           937
Lidcombe          884
Beverly Hills     866
Ryde              831
Wahroonga         811
Greenacre         793
Greystanes        771
Liverpool         763
Pennant Hills     738
Holroyd           703
Casula            700
Name: count, dtype: int64


Column: Traffic_Volume
Type: object
Top 20 most frequent values:
Traffic_Volume
Unknown     65260
Heavy       15760
Moderate     4241
Light         350
Name: count, dtype: int64


Column: SA2_CODE21
Type: int64
Top 20 most frequent values:
SA2_CODE21
117031644    2518
121041417    2127
121021404    1821
125031481    1550
126011496    1542
117011325    1402
119041668    1289
116031318    1270
120021389    1179
125041718    1076
118011345    1041
120031396    1035
125041589     998
121021406     924
127031523     911
120031681     833
127031522     799
125011586     777
119031370     774
121031409     760
Name: count, dtype: int64


Column: SA3_CODE21
Type: int64
Top 20 most frequent values:
SA3_CODE21
11703    7729
12504    4965
12003    4002
11901    3912
12102    3749
12104    3712
11904    3367
11701    3292
12703    3231
12503    3052
12602    2886
11902    2673
11603    2460
12103    2290
12101    2241
12501    2166
12601    1888
11801    1870
12702    1863
12203    1815
Name: count, dtype: int64


Column: SA3_NAME21
Type: object
Top 20 most frequent values:
SA3_NAME21
Sydney Inner City                   7729
Parramatta                          4965
Strathfield - Burwood - Ashfield    4002
Bankstown                           3912
Hornsby                             3749
North Sydney - Mosman               3712
Kogarah - Rockdale                  3367
Botany                              3292
Liverpool                           3231
Merrylands - Guildford              3052
Ryde - Hunters Hill                 2886
Canterbury                          2673
Mount Druitt                        2460
Ku-ring-gai                         2290
Chatswood - Lane Cove               2241
Auburn                              2166
Pennant Hills - Epping              1888
Eastern Suburbs - North             1870
Fairfield                           1863
Warringah                           1815
Name: count, dtype: int64


Column: SA4_CODE21
Type: int64
Top 20 most frequent values:
SA4_CODE21
117    12018
121    11992
119    11761
125    11600
120     7359
127     6210
116     4946
126     4774
124     3563
122     2784
118     2623
115     2135
128     2053
123     1793
Name: count, dtype: int64


Column: SA4_NAME21
Type: object
Top 20 most frequent values:
SA4_NAME21
Sydney - City and Inner South             12018
Sydney - North Sydney and Hornsby         11992
Sydney - Inner South West                 11761
Sydney - Parramatta                       11600
Sydney - Inner West                        7359
Sydney - South West                        6210
Sydney - Blacktown                         4946
Sydney - Ryde                              4774
Sydney - Outer West and Blue Mountains     3563
Sydney - Northern Beaches                  2784
Sydney - Eastern Suburbs                   2623
Sydney - Baulkham Hills and Hawkesbury     2135
Sydney - Sutherland                        2053
Sydney - Outer South West                  1793
Name: count, dtype: int64


Column: AREASQKM21
Type: float64
Top 20 most frequent values:
AREASQKM21
3.2122     2518
1.9142     2127
81.7548    1821
5.6086     1550
13.2936    1542
8.9106     1402
4.3130     1289
29.8693    1270
3.6039     1179
1.3881     1076
3.7250     1041
3.8432     1035
3.9355      998
9.9882      924
14.4902     911
3.9101      833
7.0720      799
6.4036      777
3.3909      774
10.2515     760
Name: count, dtype: int64


Column: 1_Area
Type: float64
Top 20 most frequent values:
1_Area
3.2122     2518
1.9142     2127
81.7548    1821
5.6086     1550
13.2936    1542
8.9106     1402
4.3130     1289
29.8693    1270
3.6039     1179
1.3881     1076
3.7250     1041
3.8432     1035
3.9355      998
9.9882      924
14.4902     911
3.9101      833
7.0720      799
6.4036      777
3.3909      774
10.2515     760
Name: count, dtype: int64


Column: 2_ML
Type: float64
Top 20 most frequent values:
2_ML
0.000000     28698
34.171878     2518
26.802372     2127
34.776168     1821
14.009320     1550
32.246711     1542
11.070945     1402
34.923457     1289
53.942509     1270
3.969655      1179
10.502698     1076
7.058585      1041
16.727619     1035
9.698544       998
18.647592      924
14.353697      911
23.683342      799
7.189455       777
31.799411      774
7.158851       746
Name: count, dtype: int64


Column: 3_TRL
Type: float64
Top 20 most frequent values:
3_TRL
0.000000     23791
0.209249      2127
4.920704      1550
8.952339      1542
1.976420      1402
3.138923      1289
5.195971      1270
8.689532      1179
2.481691      1076
14.536661     1035
8.941532       998
7.487426       924
10.022339      911
6.459979       833
9.960382       799
14.745657      777
2.791655       774
16.895499      760
2.097842       745
8.005550       735
Name: count, dtype: int64


Column: 4_PRL
Type: float64
Top 20 most frequent values:
4_PRL
0.000000     12114
2.355749      2518
5.460735      2127
23.994276     1821
6.822032      1550
7.362372      1542
17.165086     1402
4.358145      1289
4.010589      1270
2.852222      1179
0.498938      1076
12.921691     1041
0.016410       998
1.433834       924
4.738756       911
0.329723       799
1.193868       774
2.769022       760
15.885392      746
7.903368       745
Name: count, dtype: int64


Column: 5_SRL
Type: float64
Top 20 most frequent values:
5_SRL
0.000000     6957
6.678012     2518
1.953894     2127
7.860223     1550
2.310562     1542
1.501439     1289
8.485141     1270
3.064664     1179
2.038320     1076
4.968148     1041
3.585528     1035
1.416884      998
5.374095      924
4.970993      911
5.649951      833
4.943749      799
10.141134     777
2.513120      774
0.800176      760
3.114614      746
Name: count, dtype: int64


Column: 6_TrRL
Type: float64
Top 20 most frequent values:
6_TrRL
11.009615    2518
4.802336     2127
3.445904     1821
7.342863     1550
5.986376     1542
4.876993     1402
3.801463     1289
15.245359    1270
2.431615     1179
1.267512     1076
5.721989     1041
3.233405     1035
5.140331      998
3.225691      924
12.550066     911
0.062437      833
4.192281      799
5.680912      777
3.023858      774
9.299488      760
Name: count, dtype: int64


Column: 7_RRL
Type: float64
Top 20 most frequent values:
7_RRL
7.505059     2518
12.860302    2127
43.788934    1821
40.855881    1550
67.291924    1542
0.000000     1402
31.103881    1289
4.427393     1270
30.467536    1179
14.357636    1076
21.517297    1041
17.498733    1035
32.486126     998
60.325810     924
70.371563     911
33.855351     833
48.719445     799
46.992913     777
32.706618     774
61.157433     760
Name: count, dtype: int64


Column: 8_LsRL
Type: float64
Top 20 most frequent values:
8_LsRL
0.000000    59472
0.615814     2518
0.194666     2127
0.308033     1179
0.393921     1041
0.086931      924
0.083428      799
0.415295      777
1.216816      667
1.444845      640
0.096625      634
0.499148      572
0.397452      550
0.228591      547
0.105176      539
0.047706      511
0.063458      478
0.177886      470
0.804736      440
1.044424      412
Name: count, dtype: int64


Column: 9_URL
Type: float64
Top 20 most frequent values:
9_URL
0.000000     13185
9.236466      2518
3.361680      2127
0.286764      1821
6.192691      1550
1.074018      1542
3.141233      1402
2.714130      1289
31.189607     1270
2.956881      1179
2.159705      1041
1.273885      1035
0.512046       998
0.958115       924
4.173559       911
0.267903       833
0.241861       799
2.505129       777
3.525824       746
0.739679       745
Name: count, dtype: int64


Column: 10_ToRL
Type: float64
Top 20 most frequent values:
10_ToRL
71.572593     2518
55.645234     2127
106.292046    1821
88.003714     1550
125.224302    1542
38.230677     1402
81.541438     1289
122.496569    1270
54.740138     1179
31.146795     1076
54.741336     1041
56.855831     1035
58.211873      998
97.539494      924
121.180973     911
46.295621      833
92.154211      799
87.670495      777
74.028530      774
90.921618      760
Name: count, dtype: int64


Column: 11_EoR
Type: float64
Top 20 most frequent values:
11_EoR
0.658489    2518
0.633019    2127
0.518541    1821
0.702689    1550
0.563783    1542
0.581767    1402
0.583030    1289
0.660019    1270
0.629302    1179
0.564609    1076
0.690019    1041
0.648736    1035
0.547443     998
0.519718     924
0.600655     911
0.347041     833
0.549916     799
0.604948     777
0.503572     774
0.417208     760
Name: count, dtype: int64


Column: 12_NoN
Type: int64
Top 20 most frequent values:
12_NoN
254    2539
278    2518
328    1949
325    1684
460    1678
447    1550
103    1443
317    1408
310    1300
266    1244
454    1209
367    1201
217    1141
120    1076
356    1041
232    1036
494    1005
365    1001
274     944
456     924
Name: count, dtype: int64


Column: 13_NDEs
Type: int64
Top 20 most frequent values:
13_NDEs
40     3671
18     3150
45     3085
48     2405
115    2337
43     2296
54     1880
19     1824
116    1821
51     1784
25     1635
7      1588
38     1476
39     1455
46     1451
4      1415
184    1213
21     1204
34     1203
20     1125
Name: count, dtype: int64


Column: 14_NNC2L
Type: int64
Top 20 most frequent values:
14_NNC2L
0     13238
5     11935
3      8864
2      7959
4      7856
6      7684
7      7317
1      7279
8      3954
9      3209
13     2653
10     1615
11     1429
45      198
15      170
18      167
12       84
Name: count, dtype: int64


Column: 15_NNC3L
Type: int64
Top 20 most frequent values:
15_NNC3L
176    3589
186    2518
296    2469
188    2388
202    2323
217    2044
325    1550
85     1404
263    1402
163    1344
227    1289
81     1139
105    1109
256    1079
251    1041
169    1013
155     948
211     929
320     924
330     917
Name: count, dtype: int64


Column: 16_NNC4L
Type: int64
Top 20 most frequent values:
16_NNC4L
29    5194
28    5016
10    3670
31    3483
41    3345
19    2884
54    2724
36    2634
34    2606
44    2555
30    2460
23    2359
47    2155
42    1993
25    1920
43    1821
26    1782
64    1743
17    1485
11    1484
Name: count, dtype: int64


Column: 17_AND
Type: float64
Top 20 most frequent values:
17_AND
3.071942    2518
2.787402    2127
2.323171    1821
2.899329    1550
2.597826    1542
3.048544    1402
2.800000    1289
2.825806    1270
3.083333    1198
2.833787    1179
2.910112    1041
2.990783    1035
2.804511     998
2.578947     924
2.797227     911
2.991228     833
2.524291     799
3.016667     777
2.662461     774
2.715859     760
Name: count, dtype: int64


Column: 18_NE
Type: int64
Top 20 most frequent values:
18_NE
678    2836
465    2611
384    2127
381    1821
641    1559
627    1542
177    1402
484    1289
477    1270
372    1224
539    1179
450    1145
204    1076
562    1041
356    1035
547    1022
402     998
374     956
605     924
819     911
Name: count, dtype: int64


Column: 19_MCI
Type: float64
Top 20 most frequent values:
19_MCI
0.341198    2518
0.260437    2127
0.082949    1821
0.260967    1550
0.183607    1542
0.373134    1402
0.248062    1289
0.273171    1270
0.237311    1179
0.361702    1076
0.292786    1041
0.326340    1035
0.259962     998
0.165380     924
0.211488     911
0.325942     833
0.150560     799
0.310180     777
0.222576     774
0.208195     760
Name: count, dtype: int64


Column: 20_CoI
Type: float64
Top 20 most frequent values:
20_CoI
0.001288    2518
0.001727    2127
0.002266    1821
0.000974    1550
0.001172    1542
0.003306    1402
0.001390    1289
0.001365    1270
0.001266    1179
0.002898    1076
0.001129    1041
0.001717    1035
0.001650     998
0.001248     924
0.000861     911
0.001634     833
0.001204     799
0.000915     777
0.001528     774
0.001107     760
Name: count, dtype: int64


Column: 21 NBS
Type: int64
Top 20 most frequent values:
21 NBS
179    2640
121    2436
239    2094
77     2003
195    1821
216    1656
13     1402
210    1362
86     1348
129    1318
85     1289
90     1273
134    1270
69     1241
60     1190
181    1159
208    1157
122    1133
149    1083
59     1076
Name: count, dtype: int64


Column: 22_CA
Type: float64
Top 20 most frequent values:
22_CA
0.0000     6783
1.7114     2518
0.2657     2127
0.0916     1821
0.8437     1550
0.2145     1542
2.5829     1402
0.1589     1289
11.2626    1270
0.1252     1179
0.1779     1158
0.1662     1076
0.7376     1041
0.2593     1035
0.1010      998
0.1266      936
0.1757      924
0.3947      911
0.1512      799
0.2552      777
Name: count, dtype: int64


Column: 23_EA
Type: float64
Top 20 most frequent values:
23_EA
0.0000    5208
0.0448    2939
0.2373    2127
0.1620    1821
0.1512    1550
0.3761    1542
0.0681    1298
0.1234    1179
0.0198    1076
0.1094    1041
0.0531    1035
0.1006     998
0.2763     924
0.1913     911
0.2349     833
0.1704     799
0.4078     777
0.0954     774
0.3820     760
0.0834     746
Name: count, dtype: int64


Column: 24_HA
Type: float64
Top 20 most frequent values:
24_HA
0.0000    54367
0.0141     2518
0.6055     1179
0.0198     1041
0.0236      998
0.0099      924
0.0080      783
0.0802      777
0.0143      762
0.0238      745
0.0496      735
0.2215      667
0.6732      653
0.0327      640
0.4614      634
0.0609      628
0.1011      610
0.0265      586
0.3842      544
0.0040      512
Name: count, dtype: int64


Column: 25_IA
Type: float64
Top 20 most frequent values:
25_IA
0.0000    45760
0.1692     1550
0.2091     1289
7.0192     1270
0.4633     1179
0.8485     1035
0.2427      924
3.3610      911
1.5921      777
0.7949      746
1.1277      735

distance_to_CBD
17.897837    203
3.323727     188
13.212077    166
10.982541    158
12.682154    127
12.922649    116
3.163263     103
4.106571     101
2.300143      97
15.425633     91
19.760032     88
23.332321     86
34.878124     85
21.872266     84
20.337670     82
4.866625      80
19.358326     78
19.874923     78
19.758812     77
8.711772      75
Name: count, dtype: int64

In [58]:
df.to_csv('merged-unlabeled.csv',index=False)

In [59]:
df.columns

Index(['Main_Category', 'Longitude', 'Latitude', 'Day', 'duration',
       'Primary_Vehicle', 'Secondary_Vehicle', 'Is_Major_Incident', 'Advice_A',
       'Advice_B', 'Closure_Type', 'Direction', 'Main_Street',
       'Affected_Lanes', 'Actual_Number_of_Lanes ', 'Suburb', 'Traffic_Volume',
       'SA2_CODE21', 'SA3_CODE21', 'SA3_NAME21', 'SA4_CODE21', 'SA4_NAME21',
       'AREASQKM21', '1_Area', '2_ML', '3_TRL', '4_PRL', '5_SRL', '6_TrRL',
       '7_RRL', '8_LsRL', '9_URL', '10_ToRL', '11_EoR', '12_NoN', '13_NDEs',
       '14_NNC2L', '15_NNC3L', '16_NNC4L', '17_AND', '18_NE', '19_MCI',
       '20_CoI', '21 NBS', '22_CA', '23_EA', '24_HA', '25_IA', '26_OA',
       '27_PA', '28_PrA', '29_RA', '30_TA', '31_WbA', '32_EoLU', '33_TP',
       '34_PD0MV', '35_PD1MV', '36_PD2MV', '37_PD3MV', '38_PD≥4MV', '39_PUE',
       '40_AMI', '41_NPTtWbyPT', '42_NPTtWbyTx', '43_NPTtWbyCD',
       '44_NPTtWbyCP', '45_NPTtWbyO', '46_NPWfH', '47_PWCJH', '48_PBCJH',
       '49_ANP_FH', 'Tow Truck', 'Motorway Crew', 'Mechanic',
       'Heavy vehicle tow truck', 'Tow truck', 'Emergency services',
       'Transport for NSW', 'Motorway crew', 'Emergency service(s)', 'RMS',
       'Incident_Type', 'Num_Vehicles_Involved', 'Month', 'Hour',
       'distance_to_CBD'],
      dtype='object')

In [ ]:
# import pandas as pd
# from ydata_profiling import ProfileReport


# profile = ProfileReport(df, title="Profiling Report")

# profile.to_notebook_iframe()

# # To save the report to an HTML file
# profile.to_file("profiling_report.html")

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]